### ISSUE TITLE
Release 1.6.1 does not include `configure` script

### ISSUE THREAD

**Issue by fxcoudert** [rrthomas/enchant#113]
Release 1.6.1 does not include `configure` script. Please include the autogenerated files into release tarballs so users don't need the full `autoconf`/`automake`/... suite for building.

**Comment by rrthomas** [comment]
Apologies, this was an oversight. I've uploaded a dist tarball built from the release tag to the release.

**Comment by JCount** [comment]
Thank you @rrthomas
