### ISSUE TITLE
Download for release 1.6.1 broken

### ISSUE THREAD

**Issue by Ede123** [rrthomas/enchant#119]
The download link for release 1.6.1 is broken.

When opening https://github.com/AbiWord/enchant/releases/download/enchant-1-6-1/enchant-1.6.1.tar.gz :
```XML
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Key>releases/11597971/e9bac7b0-072a-11e7-89ff-c8b5d418a00b.gz</Key>
  <RequestId>900190BA9D321DC8</RequestId>
  <HostId>QpYwwWqKnZX6Ns1oSd+QxXeXCTXXhpeW+aXl88Z6fIIimCMDxLKlyCpHGYfx7Y6NP9xs7jDzspc=</HostId>
</Error>
```

Also the homepage (https://abiword.github.io/enchant/) doesn't make any mention about the new release. Is 1.6.1 supposed to be official/stable and preferable compared to 1.6.0? Or more of a release candidate?

**Comment by rrthomas** [comment]
Apologies for the missing tarball, I uploaded it but didn't try to download it again. This time I've uploaded it and tested that I can download it.

I've added the 1.6.1 release to the home page (it's a regular release).
