### ISSUE TITLE
Support TeX format

### ISSUE THREAD

**Issue by PanderMusubi** [rrthomas/enchant#12]
Please support files in TeX format as not all underlying spell checkers support this. See also http://bugzilla.abisource.com/show_bug.cgi?id=13089 and see implementation in aspell (or ispell).

**Comment by rrthomas** [comment]
I don't think this is a good idea: there's a pretty much arbitrary number of syntaxes that could be supported (e.g. consider XML, HTML, which have similar issues with tags versus plain text).

This should really be up to the controlling program (text editor &c.) to sort out, and make sure that only actual words are sent to the spell-checker.

**Comment by PanderMusubi** [comment]
Thanks for explaination. If this becomes "won't fix", please also update the bug at AbiSource's Bugzilla.

**Comment by hfiguiere** [comment]
agreed, WONTFIX.

**Comment by hfiguiere** [comment]
Thanks a lot for your report.
