### ISSUE TITLE
Use libhunspell and not old forked code

### ISSUE THREAD

**Issue by PanderMusubi** [rrthomas/enchant#13]
When Hundpell is being users, old forked code is being used. This might be okay on systems for which no libhunspell exists, but for the majority of the systes, libhunspell should be used in order to have the advantage of any bugfixes made in libhunspell. See also http://bugzilla.abisource.com/show_bug.cgi?id=13082

**Comment by TingPing** [comment]
`--with-system-myspell=yes`

**Comment by PanderMusubi** [comment]
This is the build tag Ubuntu and Debian should be using? Or does disable fallback on shipped/forked myspell code?

**Comment by rrthomas** [comment]
See PR #15, which removes the old code.

**Comment by hfiguiere** [comment]
Resolved with PR #15
