### ISSUE TITLE
Website: add link to gspell (new GTK+ library)

### ISSUE THREAD

**Issue by ghost** [rrthomas/enchant#136]
On the new Enchant website, in the section "Programs using Enchant", there is a link to GtkSpell but not to gspell.

See:
https://wiki.gnome.org/Projects/gspell
https://wiki.gnome.org/Projects/gspell/FAQ

(I don't know if there is a git repository for the Enchant website, I didn't find it).

**Comment by rrthomas** [comment]
Thanks very much for the comment, I'll add a link.

The "website" is just the file `index.html` in the main enchant repo!

**Comment by ghost** [comment]
Thanks 👍
