### ISSUE TITLE
Help XMLCopyEditor get build properly with Enchant

### ISSUE THREAD

**Issue by PanderMusubi** [rrthomas/enchant#14]
Help XMLCopyEditor get build properly with Enchant in order to get Enchant used as intended. Please see https://bugs.launchpad.net/ubuntu/+source/xmlcopyeditor/+bug/1330521 to vote (after logging in) or help out.

**Comment by hfiguiere** [comment]
This is not our bug. Sorry about that.

**Comment by hfiguiere** [comment]
If the kind folks of XMLCopyEditor have question, they can surely reach out. We'd be more than welcome to try to help.

**Comment by PanderMusubi** [comment]
Roger that!

Please vote for https://bugs.launchpad.net/ubuntu/+source/xmlcopyeditor/+bug/1330521 (if you are a user of XMLCopyEditor)
