### ISSUE TITLE
Make Enchant 2 parallel-installable with Enchant 1

### ISSUE THREAD

**Issue by ghost** [rrthomas/enchant#162]
Enchant 2 breaks the API/ABI, so it's better to make Enchant 2 parallel-installable with Enchant 1, like GTK+ 2 and GTK+ 3.

To know how to do that, see:
https://developer.gnome.org/programming-guidelines/unstable/parallel-installability.html.en

Otherwise it's really hard for a Linux distribution to switch to Enchant 2, it means that all packages depending on Enchant must be ported to Enchant 2 at the same time, which is clearly not practical.

**Comment by rrthomas** [comment]
This should be fixed; please can you confirm that the current master branch does what is needed, or let me know if something is missing?

**Comment by ghost** [comment]
Awesome, thanks for working on this.

If I go to the install prefix:
```
$ find . -iname "*enchant*"
./lib/pkgconfig/enchant-2.pc                                                                                                                                             
./lib/libenchant-2.so.2.1.2                                                                                                                                              
./lib/libenchant-2.so.2                                                                                                                                                  
./lib/libenchant-2.so                                                                                                                                                    
./lib/libenchant-2.la                                                                                                                                                    
./lib/libenchant-2.a                                                                                                                                                     
./lib/enchant-2                                                                                                                                                          
./lib/enchant-2/enchant_hunspell.so                                                                                                                                      
./lib/enchant-2/enchant_hunspell.la                                                                                                                                      
./lib/enchant-2/enchant_hunspell.a                                                                                                                                       
./share/man/man1/enchant.1                                                                                                                                               
./share/man/man1/enchant-lsmod.1              
./share/enchant                           
./share/enchant/enchant.ordering          
./bin/enchant-lsmod-2                     
./bin/enchant-2                           
./include/enchant-2                       
./include/enchant-2/enchant.h             
./include/enchant-2/enchant-provider.h    
./include/enchant-2/enchant++.h
```

Some things don't have the `-2` suffix: the man pages and the `share/enchant` directory. I think those will conflict if Enchant 1 and Enchant 2 are both installed in the same install prefix.

**Comment by rrthomas** [comment]
This is correct, I don't propose to fix those.

The man pages, because it is not sensible to expect users to ask for `man enchant-2`.

The share directory because there is no incompatibility in `enchant.ordering` between versions. (If an incompatibility arose in a later version, then I would version the directory.)

**Comment by ghost** [comment]
OK, I'm not a Linux distro packager, so I don't know if it'll cause a problem.

**Comment by rrthomas** [comment]
Thanks, I'll look into it before making a release. But, you can confirm that it does what you need from a development point of view?

**Comment by ghost** [comment]
Yes I confirm it does what I need for [gspell](https://wiki.gnome.org/Projects/gspell).

**Comment by rrthomas** [comment]
That's great, thanks.

**Comment by ghost** [comment]
Actually there is a problem in the pkg-config file:
```
$ pkg-config --cflags enchant-2
-I/home/seb/jhbuild/include/enchant -I/home/seb/jhbuild/include/glib-2.0 -I/home/seb/jhbuild/lib/glib-2.0/include -pthread
$ pkg-config --libs enchant-2
-L/home/seb/jhbuild/lib -lenchant
```

It should be:
```
-I/home/seb/jhbuild/include/enchant-2
-lenchant-2
```

**Comment by rrthomas** [comment]
Thanks, this should be fixed now in `rrthomas/master`.

**Comment by ghost** [comment]
Yes I confirm it is fixed, gspell builds fine and all unit tests still pass. Thanks!

**Comment by rrthomas** [comment]
Excellent, thanks.
