### ISSUE TITLE
Enchant 2 not working for me, “Couldn't create a dictionary for en_US.utf8”

### ISSUE THREAD

**Issue by ghost** [rrthomas/enchant#164]
I use Fedora 27, I've tried to install Enchant 2, but it is not working for me, I have this error:
```
$ enchant-2 test-enchant2
Couldn't create a dictionary for en_US.utf8
```

I've installed Enchant 2 from the git repo, like this:
```
$ ./bootstrap
$ ./configure --prefix=/home/seb/jhbuild --without-aspell --enable-relocatable
[...]
Providers to build: hunspell
$ make
$ make install
```

I use [jhbuild](https://wiki.gnome.org/Projects/Jhbuild). On Fedora I've installed the hunspell-devel package in order to build the hunspell enchant provider. Enchant 1.6.0 installed by Fedora works fine, it finds the dictionaries (including `en_US`).

I don't know why Enchant 2 doesn't find the `en_US` dictionary.

**Comment by rrthomas** [comment]
What does `enchant-lsmod-2` say? And then `enchant-lsmod-2 -lang en_US`?

**Comment by ghost** [comment]
```
$ enchant-lsmod-2
hunspell (Hunspell Provider)
```

**Comment by rrthomas** [comment]
And then `enchant-lsmod-2 -lang en_US`? Most likely, you need to specify `--with-hunspell-dir`. (Hunspell doesn't have a built-in location for its dictionaries.)

**Comment by ghost** [comment]
OK indeed I see in the RPM *.spec for Enchant 1.6 that there is `--with-myspell-dir=/usr/share/myspell`.

So for Enchant 2, I've added `--with-hunspell-dir=/usr/share/myspell` and it now works fine:
```
$ enchant-lsmod-2 -lang en_US
en_US (hunspell)
```

Thanks for your help!

**Comment by rrthomas** [comment]
This could be better documented. Reopening to remind me.
