### ISSUE TITLE
Double free or corruption with -list-dicts

### ISSUE THREAD

**Issue by nathan-thenut** [rrthomas/enchant#167]
Hi,
`enchant-lsmod -list-dicts` crashes on me with this error message:

```
*** Error in `enchant-lsmod': double free or corruption (out): 0x00007fffdc030a60 ***
[1]    6090 abort (core dumped)  enchant-lsmod -list-dicts
```
The full gdb log is here: https://paste.xinu.at/AgJ/

Originally I stumbled upon this through an issue with the twitter client corebird:
https://github.com/baedert/corebird/issues/799

**Comment by rrthomas** [comment]
I am guessing from the corebird issue you point to, where `enchant-lsmod` lists some providers twice, that Enchant 2 is getting built in such a way that it picks up Enchant 1's providers, which is not going to work. I suggest you make sure you're using the latest version, 2.1.3 (which is properly parallel installable), and try again.

**Comment by nathan-thenut** [comment]
m( Ah damn. I have enchant 1.6 and 2.1.2 installed because gnucash and webkitgtk2 are still dependent on enchant 1.6... Damn. Now I need to rebuild webkitgtk _sigh_

**Comment by rrthomas** [comment]
It shouldn't be necessary to rebuild webkitgtk2. Just use Enchant 2.1.3, which has versioned directories. This should only be a problem still if you have providers installed in your per-user config directory.
