### ISSUE TITLE
Side-by-side installation of enchant-1.x and 2.x

### ISSUE THREAD

**Issue by manisandro** [rrthomas/enchant#168]
I'm looking at packaging enchant-2.x for Fedora as a separate package, so that it can install side-by-side with enchant-1.x (to avoid issues with packages not yet ported to enchant-2.x). I have the following questions:
- Could the pkgdatadir be changed to `$prefix/share/enchant-2` instead of `$prefix/share/enchant` (in line with other files installed by enchant-2.x which are also suffixed with the major version)?
- Same applies to the man pages
- Does the folder in the user profile directory also need to be suffixed, or are those files usable by both enchant-1.x and 2.x?

Thanks.

**Comment by rrthomas** [comment]
I didn't change `pkgdatadir` because there's no incompatibility, and no reason to configure two versions differently system-wide. The user folders don't need a suffix either.

I didn't change the man pages because having to type `man enchant-2` is just wrong. Can you suggest something better? What do other Fedora packages do? (I tried and failed to find the answer in Debian.)

**Comment by manisandro** [comment]
Thanks for the reply. Ok for the data dir. As for the man page, typically the name of the man page should match the name of the program. So, even though `enchant-2` might look odd, it is consistent with the program name (and I suppose the synopsis in the manpage text should be updated as well). If the dash is disturbing, perhaps it could be called just `enchant2`, but I don't know whether it is worth it. Beyond that I'm afraid I have no better ideas.

As far as packaging specifically is concerned, there is a general "no conflicts" policy, but beyond that it is up to the packager do decide how to resolve potential conflicts. Typically it is just adding the major version somewhere, as was already done for most of the files in enchant anyway.

**Comment by rrthomas** [comment]
Thanks. This does indeed seem to be done for some other programs, now that I simply do `ls /usr/bin/*2` and then try `man foo2` for some of them.

**Comment by manisandro** [comment]
To come back to the data dir:

    $ diff -u /usr/share/enchant/enchant.ordering  /usr/share/enchant-2/enchant.ordering 
    --- /usr/share/enchant/enchant.ordering 2017-08-03 00:07:57.000000000 +0200
    +++ /usr/share/enchant-2/enchant.ordering       2017-09-08 15:32:21.000000000 +0200
    @@ -1,8 +1,7 @@
    -*:myspell,aspell,ispell
    -fi:voikko,ispell,myspell,aspell
    -fi_FI:voikko,ispell,myspell,aspell
    -he:hspell,myspell
    -he_IL:hspell,myspell
    -yi:uspell
    +*:hunspell,aspell
    +fi:voikko,hunspell,aspell
    +fi_FI:voikko,hunspell,aspell
    +he:hspell,hunspell
    +he_IL:hspell,hunspell
    tr:zemberek
    tr_TR:zemberek

It looks to me as if they aren't really compatible, given the myspell -> hunspell rename?

**Comment by rrthomas** [comment]
Uninstalled providers are ignored, so just put both names if you want the configuration file to work with both versions.

**Comment by rrthomas** [comment]
Please could you have a look at current master head and check whether the man page changes work for you?

**Comment by manisandro** [comment]
The manpages work great, I've already tested with the commit in your branch. Thanks for that!

About the data: From a packaging point of view, this is a bit messy. The only way I suppose would be to carry downstream an adapted `enchant.ordering` which contains providers for for both enchant-1.x and 2.x, and ship this file as co-owned in both the `enchant` and `enchant2` packages, but I can't have one package modify the other package's files.

**Comment by rrthomas** [comment]
Just configure appropriately, with a suitable `--datadir` argument to `configure`.

**Comment by manisandro** [comment]
Yeah suppose I'll go that way. Thanks.

**Comment by rrthomas** [comment]
Actually, it's `pkgdatadir` that needs to be redefined. This can't be done with `configure`. Debian's `gnupg2` package achieves this by patching the package name in `configure.ac`. However,

`make pkgdatadir=/usr/share/enchant-2`

seems to work. It would be good to know if that's good enough, so I can document this for other packagers.

I can't think of an easy way to make it work for both users installing from source (where allowing e.g. 2.1.x's files to overwrite 1.6.x's will work fine, possibly with reconfiguration to cope with the myspell→hunspell rename), and packagers (who may want to have separate files by default, and then use some distro-specific mechanism to allow them to be linked together where possible).

**Comment by manisandro** [comment]
Yep that works indeed, thanks!
