### ISSUE TITLE
Finding per-dictionary character classes

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/enchant#17]
Enchant seems to provide no way to find a given dictionary's definition of code points that can appear in a word (lazily, its word character classes).

Emacs's spelling code requires two essential pieces of information:

1. A class of "case characters".
2. A class of "otherchars", which are characters not in "case characters" that are allowed in words, e.g. dash, apostrophe.

For most of the underlying spelling engines, such as aspell and hunspell, this information can be found in the underlying dictionaries (and Emacs does so when using them directly).

However, Enchant does not seem to expose this information. This begs the question, what do other Enchant clients do?

**Comment by rrthomas** [comment]
@JMLas, any comments?

**Comment by JMLas** [comment]
As far as our use in LyX is concerned, we have a bug open somewhere telling that we should use this kind of information ;) But it never occured to me that the information was available in the dictionaries. I always thought that emacs used its own per-language list of special characters.

**Comment by rrthomas** [comment]
Thanks, that's interesting. Emacs assumes [:alpha:] for ispell and aspell dictionaries, but for hunspell it parses the dictionary files to get the information. However, hunspell does not make this information available via their APIs, as far as I can tell.

[Comment edited to fix a couple of errors.]

**Comment by rrthomas** [comment]
Hunspell has `get_wordchars`, which returns the value of the `WORDCHARS` keyword in the current affix file (effectively Emacs's "otherchars"). The full class of word characters is that plus those characters considered to be letters.

**Comment by rrthomas** [comment]
Fixed by PR #139.
