### ISSUE TITLE
Return value of g_convert unchecked

### ISSUE THREAD

**Issue by baedert** [rrthomas/enchant#170]
In https://github.com/AbiWord/enchant/blob/master/providers/enchant_hspell.c#L80, the return value of the `g_convert` call is not checked, and no error argument is provided. `g_convert` returns `NULL` in the error case which later is passed to `hspell_check_word` which does not guard for a `NULL` word and simply dereferences it.

This seems to be a new problem. git blame points to 32f236e69df1b802fc09fb7be4a0964bbe050695 which removes a `if (iso_word == NULL || !is_hewbrew (iso_word, length))` check. I assume this was unindented?

**Comment by rrthomas** [comment]
Good catch, thanks! I think you mean "unintended", though!

**Comment by PeterBloomfield** [comment]
Calling g_free (iso_word) when iso_word is known to be NULL seems redundant. Or is there some arcane stylistic reason for it?

**Comment by rrthomas** [comment]
Good catch, just a left-over.
