### ISSUE TITLE
Spellchecking umlauts for language Hebrew segfaults

### ISSUE THREAD

**Issue by felixfontein** [rrthomas/enchant#180]
As noticed in jamiemcg/Remarkable#222, it is possible to trigger a segfault when asking enchant on Arch Linux (x86_64) to spellcheck an Umlaut (äöü) for language Hebrew.

Here's a simple test program:
```
#include <enchant/enchant.h>

int main() {
    EnchantBroker * broker = enchant_broker_init();
    EnchantDict * dict = enchant_broker_request_dict(broker, "he");
    const char * word = "ä";
    enchant_dict_check(dict, word, -1);
}
```
Compiling and running it with `gcc -o test test.cpp -lenchant && ./test` leads to `Segmentation fault (core dumped)` on my machine:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5b2a976 in hspell_check_word () from /usr/lib/libhspell.so.0
(gdb) bt
#0  0x00007ffff5b2a976 in hspell_check_word () from /usr/lib/libhspell.so.0
#1  0x00007ffff5d32ca6 in ?? () from /usr/lib/enchant/enchant_hspell.so
#2  0x0000555555554827 in main ()
```
(Output of `uname -a`: `Linux xxx 4.14.8-1-ARCH #1 SMP PREEMPT Wed Dec 20 21:27:44 UTC 2017 x86_64 GNU/Linux`)

I don't know if this is hspell's fault or enchant's, or if it happens on other systems than Arch, so I'm filing the bug here.

**Comment by rrthomas** [comment]
Thanks very much for the reproducer and report; this is a bug where Enchant fails to reject an invalid string (that is, one containing characters that cannot be represented in ISO-8859-8). This should give an error not a crash.

I am working on a patch and will make a new release as soon as it is ready.

**Comment by felixfontein** [comment]
Thank you very much for the quick reaction and fix!

**Comment by rrthomas** [comment]
You're very welcome. Closing. New release coming up.
