### ISSUE TITLE
running 'make check' tries to delete my system libraries

### ISSUE THREAD

**Issue by themaddoctor** [rrthomas/enchant#185]
No shit, it did.

tar -xf enchant-2.2.1.tar.gz
cd enchant-2.2.1
./configure --prefix=/usr --libdir=/usr/lib64 --enable-relocatable
make
make check
...
rm: cannot remove '/usr/lib64/ts/dejitter.so': Permission denied
rm: cannot remove '/usr/lib64/ts/touchkit.so': Permission denied
rm: cannot remove '/usr/lib64/ts/touchkit.la': Permission denied
rm: cannot remove '/usr/lib64/ts/iir.so': Permission denied
rm: cannot remove '/usr/lib64/ts/pthres.so': Permission denied
rm: cannot remove '/usr/lib64/ts/iir.la': Permission denied
rm: cannot remove '/usr/lib64/ts/linear.la': Permission denied
rm: cannot remove '/usr/lib64/ts/skip.so': Permission denied
rm: cannot remove '/usr/lib64/ts/skip.la': Permission denied
rm: cannot remove '/usr/lib64/ts/debounce.so': Permission denied
rm: cannot remove '/usr/lib64/ts/invert.so': Permission denied
rm: cannot remove '/usr/lib64/libQt5Sql.so.5': Permission denied
rm: cannot remove '/usr/lib64/libcupsimage.so.2': Permission denied
make[4]: *** [Makefile:1550: libenchant-copy] Error 1
make[4]: Leaving directory '/building/inkscape/enchant-2.2.1/tests/enchant_providers'
make[3]: *** [Makefile:1547: usr/lib64/libenchant-2.la] Error 2
make[3]: Leaving directory '/building/inkscape/enchant-2.2.1/tests/enchant_providers'
make[2]: *** [Makefile:1411: check-am] Error 2
make[2]: Leaving directory '/building/inkscape/enchant-2.2.1/tests/enchant_providers'
make[1]: *** [Makefile:1833: check-recursive] Error 1
make[1]: Leaving directory '/building/inkscape/enchant-2.2.1/tests'
make: *** [Makefile:865: check-recursive] Error 1

**Comment by rrthomas** [comment]
Just seen this. Wow! I'm really sorry. I think I can see where the problem is, and I'm looking into it right now.

**Comment by rrthomas** [comment]
Update: the problem is that `configure.ac` assumes that `libdir` will start with `exec_prefix`, which in your case it obviously doesn't, having configured `libdir` specifically.

**Comment by rrthomas** [comment]
(Previous comment deleted, as wrong.)

I think the problem is that `${exec_prefix}` is not correctly expanded. Like some other tricks, the expansion should be deferred to the Makefile. Working on a fix now.

**Comment by iamleot** [comment]
This seems that still happens with `enchant-2.2.3` and probably also the latest
`master` (on NetBSD-current) and it is actually an `rm -rf /` (so please be careful if you would like to reproduce the following steps!):

````
% tar xzf enchant-2.2.3.tar.gz
% cd enchant-2.2.3
% ./configure --enable-relocatable
[...]
% make
[...]
% make check
[...]
mv -f Provider/.deps/providers_test-provider_request_dict.Tpo Provider/.deps/providers_test-provider_request_dict.Po
make libenchant-copy
rm -rf /
rm: /usr/bin/agrep: Permission denied
rm: /usr/bin/atf-config: Permission denied
[...]
````

After a quick skim I think that the following `rm -rf' are the problematic ones
(probably same one of the issue reported), in tests/Makefile.am:

````
    35  libenchant-copy:
    36          rm -rf $(libdir_subdir)/
    37          $(MKDIR_P) $(libdir_subdir)/enchant-@ENCHANT_MAJOR_VERSION@
    38          cp -r $(top_builddir)/src/@objdir@ $(libdir_subdir)/
    39          cp $(top_builddir)/src/libenchant-@ENCHANT_MAJOR_VERSION@.la $(libdir_subdir)/
````

...and in tests/enchant_providers/Makefile.am

````
    30  libenchant-copy:
    31          rm -rf $(libdir_subdir)/
    32          $(MKDIR_P) $(libdir_subdir)/enchant-@ENCHANT_MAJOR_VERSION@
    33          cp -r $(top_builddir)/src/@objdir@ $(libdir_subdir)/
    34          cp $(top_builddir)/src/libenchant-@ENCHANT_MAJOR_VERSION@.la $(libdir_subdir)/
````

I think it would be better to remove the trailing "/" and then try
to adjust `libdir_subdir` as neeeded.
