### ISSUE TITLE
test suite fails version 2.2.2

### ISSUE THREAD

**Issue by themaddoctor** [rrthomas/enchant#187]
Just tried 2.2.2, and although "make check" did not try to delete my libraries,
it still failed. Here is the test-suite.log file:

[check.log](https://github.com/AbiWord/enchant/files/1692301/check.log)

**Comment by themaddoctor** [comment]
linux 64 with GCC 7.1.0 and glibc 2.26

**Comment by rrthomas** [comment]
Are you using GNU Make? (I assume so, on Linux.)

What does `grep libdir_subdir tests/Makefile` say? (This is nothing to do with the test suite, it's the build system.)

**Comment by rrthomas** [comment]
OK, somehow it was passing on my system although I failed to check for GNU make properly.

**Comment by rrthomas** [comment]
Oh darn it, I left a test not sign in and reversed the sense of the GNU Make test.

**Comment by themaddoctor** [comment]
I'm not sure if you are asking me a question, so I will just wait here
for a bit.


On 2/3/18, Reuben Thomas <notifications@github.com> wrote:
> Oh darn it, I left a test not sign in and reversed the sense of the GNU Make
> test.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AbiWord/enchant/issues/187#issuecomment-362868230


-- 
Thomas Kaeding

my public key: http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F

**Comment by rrthomas** [comment]
The sentences ending in question marks were questions (first comment), but then I worked out what was wrong myself (second comment). I have uploaded a PR with the fix, and assuming the builds pass, will release tomorrow. Thanks for the report!

**Comment by themaddoctor** [comment]
Will try it then.


On 2/3/18, Reuben Thomas <notifications@github.com> wrote:
> The sentences ending in question marks were questions (first comment), but
> then I worked out what was wrong myself (second comment). I have uploaded a
> PR with the fix, and assuming the builds pass, will release tomorrow. Thanks
> for the report!
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AbiWord/enchant/issues/187#issuecomment-362869407


-- 
Thomas Kaeding

my public key: http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F

**Comment by themaddoctor** [comment]
Success. Thank you.
```
PASS: main.test
============================================================================
Testsuite summary for enchant 2.2.3
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

**Comment by rrthomas** [comment]
Great; sorry the bug was there in the first place, and that it took two goes to fix properly!
