### ISSUE TITLE
Include gnulib in release tarballs

### ISSUE THREAD

**Issue by darkxst** [rrthomas/enchant#191]
I am currently trying to package enchant 2 for debian/ubuntu. 

gnulib in the debian archives is too old (snapshot from 2014), but besides gnulib is not really meant to be packaged in distro's.

Your bootstrap script pulls in gnulib from git, which works fine for a local build, but would not be acceptable in debian packaging. 

It would perhaps be better if you had a gnulib snapshot in your release tarballs

**Comment by rrthomas** [comment]
If you're building from a tarball, you shouldn't be running `bootstrap`. If the documentation is unclear on this point, please file an issue.
