### ISSUE TITLE
INSTALL file?

### ISSUE THREAD

**Issue by asmeurer** [rrthomas/enchant#193]
The HACKING file [says](https://github.com/AbiWord/enchant/blob/8ea3877062d7779a685fd326793d84dc6f8122cd/HACKING#L7) "see INSTALL". But I don't see an `INSTALL` file anywhere.

**Comment by rrthomas** [comment]
Oh dear, `INSTALL` is not checked into git, because it is a generated file. That is unhelpful. I will move the git install instructions into `HACKING`. Thanks for the report!
