### ISSUE TITLE
Is Aspell a required dependency?

### ISSUE THREAD

**Issue by rnkn** [rrthomas/enchant#197]
The Homebrew recipe for enchant currently lists Aspell as a required dependency:
https://github.com/Homebrew/homebrew-core/blob/13f92ffd43a78052942c2d1fd2b214393637a510/Formula/enchant.rb#L18

I have enchant configured to use AppleSpell exclusively, so is this requirement correct?

**Comment by rrthomas** [comment]
No. Closing as this is only informative, not an enchant issue.

**Comment by rnkn** [comment]
Thanks 👍
