### ISSUE TITLE
Relocation on Windows (mingw-w64 / MSYS2 build environment) not working

### ISSUE THREAD

**Issue by Ede123** [rrthomas/enchant#198]
It seems relocation support in enchant-2 has been reworked considerably. Unfortunately I can't seem to make it work when building enchant with mingw-w64 (in an MSYS2 build environment).

For some reason enchant fails to load the available providers. Running `enchant-lsmod-2` does not output anything (although several backends - aspell, ispell and myspell - should be available in the environment).

The pacman build file in use is at https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-enchant/PKGBUILD#L33-L43 (configure line highlighted).
* `--prefix` is set to "/mingw64" which should correctly be mapped to "C:\msys64\mingw64" in the MSYS2 environment
* I adjusted the configure line to include `--enable-relocatable` which did not improve upon the situation
* I also tried additionally removing `--prefix` (which seemed to fall back to "/usr" as a default prefix) as well as setting it to something nonexistent (not working either)

Using ProcessMonitor it seems enchant-lsmod-2 is only ever looking for the shared libraries in an absolute path derived from the `--prefix` configure option, i.e. "C:\mingw64\lib\enchant-2", instead of trying locations relative to the binary itself (I'd expect it to look in "..\lib\enchant-2", so that "C:\msys64\mingw64\bin\enchant-lsmod-2" would search in the proper directory "C:\msys64\mingw64\lib\enchant-2").

**Comment by rrthomas** [comment]
Sorry, I don't have time to work on this. Patches welcome!

**Comment by Ede123** [comment]
If I had time to work on patches I'd not have filed this report. ;-)

I had hoped it might be something "obvious" if one knows the code, but if you don't have any immediate ideas that's fine. Let's hope somebody else is bugged enough by this...

**Comment by Ede123** [comment]
Looking into this some more it seems gnulib's `relocate()` does not do any relocation at all on Windows (at least in my environment). The path is always returned unmodified.

Looking at `relocate()` in http://git.savannah.gnu.org/cgit/gnulib.git/tree/lib/relocatable.c I assume `curr_prefix` might never be set, therefore no relocation is attempted.

I found that calling `set_relocation_prefix()` via `enchant_set_prefix_dir()` works around this issue and I suggested a suitable patch for the MSYS2 project which uses glib's `g_win32_get_package_installation_directory_of_module()` to find the proper prefix, see https://github.com/Alexpux/MINGW-packages/pull/4199.

At this point I'm not sure if gnulib is supposed to find the proper prefix itself, but as enchant is already using glib this approach seemed reasonable.

**Comment by rrthomas** [comment]
`enchant_set_prefix_dir` is already provided for this purpose.

**Comment by Ede123** [comment]
That's what I used (still needs to be called somewhere with the proper prefix, though).

**Comment by rrthomas** [comment]
`set_relocation_prefix` is automatically called by `relocate` if gnulib is built with `ENABLE_COSTLY_RELOCATABLE`, which is defined to 1 on Windows.

In any case, this is not the right forum for problems with gnulib. Please ask about details on on the Gnulib discussion list: https://lists.gnu.org/mailman/listinfo/bug-gnulib

(Unless of course it looks as though enchant is not using gnulib correctly, but that doesn't seem to be the case here.)

**Comment by Ede123** [comment]
If you refer to the call early in `relocate()`:  
It is called but both `curr_prefix` and `curr_prefix_better` are `NULL` at this point.

IMHO gnulib's `compute_curr_prefix()` is broken, but the code is quite convoluted and I don't want to spend more time on debugging it.

**Comment by rrthomas** [comment]
I can assure you from my own correspondence with the gnulib maintainers when I added relocate to enchant that it is considered to be working and is maintained, so if you have problems with it, please do contact them; my experience is that they are usually quick to reply and always friendly!

I don't understand your comment, by the way: `curr_prefix_better` is assigned in `relocatable.c` line 486, just before the call to `set_relocation_prefix` in line 490.

But this is not the place to discuss gnulib. I'll close the issue; feel free to reopen it if you find that enchant is using gnulib incorrectly.

**Comment by Ede123** [comment]
> I don't understand your comment, by the way: curr_prefix_better is assigned in relocatable.c line 486, just before the call to set_relocation_prefix in line 490.

It's assigned the return value of `compute_curr_prefix()`, which is `NULL` in this case, that's why I think said function is not working properly.

The problem seems to be a mixture of different path styles as a debug statement in `relocate()` yields
```
orig_installprefix: /mingw64, orig_installdir: C:/msys64/mingw64/bin,
curr_prefix: (null), curr_prefix_better: (null)
get_shared_library_fullname: C:\msys64\mingw64\bin\libenchant-2.dll
```

The discrepancy between `orig_installprefix` and `orig_installdir` makes `compute_curr_prefix()` fail early and return `NULL`, wether this is a enchant or gnulib issue I can't really tell, though. At the very least these values come from the defines `INSTALLPREFIX` and `INSTALLDIR` though, which I guess enchant has a hand in setting.

**Comment by rrthomas** [comment]
Thanks for clarifying.

That sounds like enough for a gnulib bug report or at least question. Enchant sets `INSTALLDIR` as specified in the relocatable docs, and relocatable's autoconf machinery sets `INSTALLPREFIX`.
