### ISSUE TITLE
Could not find a version that satisfies the requirement enchant (from versions  : )

### ISSUE THREAD

**Issue by samayo** [rrthomas/enchant#200]
I have Python 3.4.4 and pip 18.0 

When I try to install enchant with pip I get the above error. 

I am running Python on windows 10, I can install other libraries except enchant.  It used to work on 3.3 about a year ago but not anymore.

Any fix for this?

**Comment by rrthomas** [comment]
Sorry, this is the C upstream; the Python bindings are maintained elsewhere. See `README`. If it is out of date, do let me know!

**Comment by samayo** [comment]
Sorry. I mean to post it on pyenchant but after searching for the error it bought me here, I thought it was the same repo :)

Just one last question since pyenchant is no longer maintained, is it possible to install your library on windows? I can't find the binary version anywhere

**Comment by rrthomas** [comment]
I don't supply binaries, but the build system has been tested on Windows, so it should build.

**Comment by samayo** [comment]
Oh ok, thanks for the help.
