### ISSUE TITLE
Backward pass lops off scandinavic characters

### ISSUE THREAD

**Issue by Technologicat** [rrthomas/enchant#212]
In [tokenize_line](https://github.com/AbiWord/enchant/blob/master/src/enchant.c#L230), the part that says *Skip backwards over any characters that can't appear at the end of a word* walks the word backward one byte at a time.

This is incorrect for utf-8 input. For example, scandinavic characters use two bytes each.

Particularly, in Finnish, this issue causes any words ending in `ä` or `ö` to have the scandinavic characters (at the end of the word) lopped off, before the word is sent to the spellchecking backend. I have confirmed my observations by strategically placing printfs in `enchant.c` (release 2.2.3; that part of the code is identical to the git HEAD).

Commenting out the backward pass makes Enchant handle Finnish correctly. I suppose the issue affects also Swedish and related languages.

**Comment by rrthomas** [comment]
Thanks for the report. I'll look into it when I can find a moment.

**Comment by Technologicat** [comment]
Ok, thanks! Let me know if you need more information.

**Comment by rrthomas** [comment]
Please could you try `rrthomas/master` and see if it fixes the problem for you? I have made a fix which skips backwards over the non-word characters a character at a time rather than a byte at a time.

**Comment by Technologicat** [comment]
Sure! I'll test it once I have the chance. (And first figure out how to build Enchant from git, it's been a while since I've used autotools.)

**Comment by rrthomas** [comment]
See `HACKING`. It's pretty straightforward: basically just install the autotools and then one extra step: `./bootstrap`.

**Comment by Technologicat** [comment]
Ah, thanks! That's exactly the command I'd forgotten during my years deving mostly on Python :)

**Comment by Technologicat** [comment]
Tested. `rrthomas/master` works, thank you!

For those following along at home: building Enchant from git seems to need `git-merge-changelog` (comes in the Ubuntu package with the same name). Check this if your `./bootstrap` fails mysteriously.

**Comment by rrthomas** [comment]
Thanks for the confirmation. `git-merge-changelog` is not required (and I don't even have it installed). `bootstrap` does mention it, but it's provided anyway by gnulib.

**Comment by Technologicat** [comment]
Ok, thanks for the clarification.

What I find weird here is that `./bootstrap` failed for me the first time. It warned about missing `git-merge-changelog`, and errored out, complaining that `LT_SYS_MODULE_EXT` may be undefined (should be [provided by gnulib](https://www.gnu.org/software/libtool/manual/html_node/Autoconf-macros.html), and these two things seem unrelated).

Installed `git-merge-changelog`, tried `./bootstrap` again, and it ran fine.

Anyway, got the build working and your fix works - maybe not worth the time to debug my installation further now. :)

**Comment by rrthomas** [comment]
It would be nice to know what the actual error was! I get that warning about `git-merge-changelog`, but it is only a warning.

**Comment by Technologicat** [comment]
I agree, would be nice to know! Trying again with `AbiWord/master`, I couldn't reproduce the bootstrap error. I'll open another issue for it later, if I figure out how to reproduce it.

In case you're interested in adding a test case for this, specifically in case of Finnish: in Ubuntu or Mint, the version of Voikko that's in the repos is fine. Words useful for testing this issue include `tämä` (this), `häiriö` (disturbance) and `tietyö` (road work) - these spellings are correct. I tested manually in a terminal with `enchant -d fi -a`, but this step could be automated.

I keep a copy of my notes [here](https://github.com/Technologicat/spacemacs.d/), along with my [Spacemacs](http://spacemacs.org/) `init.el`. I'm using Enchant as the spellchecker for Emacs and [LyX](https://www.lyx.org/).
