### ISSUE TITLE
Tests failing in Nix

### ISSUE THREAD

**Issue by jtojnar** [rrthomas/enchant#219]
I am unsuccessfully trying to run tests under Nix package manager. Nix runs all builds in a sandbox with limited environment so maybe there are some hidden assumptions causing the tests to fail.

The tests run just fine in my user profile so I tried adding `LANG=en_GB.UTF-8` to the environment but that was not enough:

[test-suite.log](https://github.com/AbiWord/enchant/files/3471493/test-suite.log)

**Comment by rrthomas** [comment]
Thanks for the report. I admit I don't have much idea what the problem could be, though I note that a lot of the failure are to do with tests that need to write to a file (e.g. pwl).

I'm sorry, I don't have time to look into this myself. It might be helpful to compare the test environment with the Travis environment (see `~/.travis.yml`).

**Comment by rrthomas** [comment]
Looks like something is wrong with the way paths are working:

```
   prefixDir: /nix/store/i2lqvs91gf3frfgfkq65layxaa8my686-enchant-2.2.4, expectedPrefixDir: .
   provider/enchant_provider_get_prefix_dir_tests.cpp:59:1: error: Failure in EnchantGetPrefixDir: (expectedPrefixDir == NULL && prefixDir == NULL) || strcmp(expectedPrefixDir, prefixDir) == 0
```

Did you configure with `--enable-relocatable`, and what is `--prefix`?

**Comment by jtojnar** [comment]
Hmm, now I see the warning:

[enchant-build.log](https://github.com/AbiWord/enchant/files/3564881/enchant-build.log)

And indeed with relocatable enabled, the ¿two? tests succeed?

[enchant-build-relocatable.log](https://github.com/AbiWord/enchant/files/3564885/enchant-build-relocatable.log)

Are there any downsides to enabling it?

**Comment by rrthomas** [comment]
Great! (There are many tests at the C++ level, but from the build system's point of view, only 2.)

There are no downsides to enabling relocatability other than a very slight slowdown in the startup of the "enchant" binary. Sorry I didn't think of this possibility earlier!
