### ISSUE TITLE
Building on Ubuntu

### ISSUE THREAD

**Issue by PanderMusubi** [rrthomas/enchant#220]
When building Enchant release 2.2.5 according to instructions in `HACKING` on Ubuntu 19.04 (Disco Dingo), the following error occurs:

    ./bootstrap && ./configure --enable-relocatable
    ...
    bootstrap: running: autoreconf --symlink --install
    configure.ac:52: error: possibly undefined macro: LT_SYS_MODULE_EXT
          If this token and others are legitimate, please use m4_pattern_allow.
          See the Autoconf documentation.
    autoreconf: autoconf failed with exit status: 1

This can be solved by:

    sudo apt-get install libltdl-dev

1) If this is correct, can `libltdl-dev` be added to https://github.com/AbiWord/enchant/blob/master/HACKING#L8 ?

See also https://packages.ubuntu.com/disco/libltdl-dev

In order to build Enchant successfully, at least development files of one backend need to be installed. For the Hunspell and Aspell backends, install the needed development files of those spell checkers with:

    sudo apt-get install libhunspell-dev libaspell-dev

2) Could package names `libhunspell-dev`, `libaspell-dev`, etc. could also be listed in `HACKING` ?

**Comment by PanderMusubi** [comment]
For being able to run `make check` the following packages needs to be installed before running the `bootstrap` script:

    sudo apt-get install libunittest++-dev

3) Can `libunittest++-dev` also be mentioned in the HACKING file?

**Comment by rrthomas** [comment]
The instructions in `HACKING` are not distro-specific. I've added a note to `HACKING` pointing to `.travis.yml` and `appveyor.yml` for some distro-specific information.

**Comment by osevan** [comment]
ok thanks
