### ISSUE TITLE
Cannot build on MinGW64

### ISSUE THREAD

**Issue by dmerejkowsky** [rrthomas/enchant#226]
Hello,

I'm the new maintainer of the PyEnchant library and we used to include a copy of enchant.dll inside our wheels.

I've been trying to build this library on Windows but I'm hitting a compile error I don't know how to fix.

You can see build scripts and full logs here:
https://github.com/pyenchant/build-enchant/

Relevant parts:

* I'm trying to build just the hunspell provider
* Hunspell was configured like this: `./configure --prefix=/mingw64`
* enchant was conffigured like this: 

```
   ./configure \
       --build=${MINGW_CHOST} \
       --host=${MINGW_CHOST} \
       --target=${MINGW_CHOST} \
       --enable-shared  \
       --enable-relocatable  \
       --prefix="${PREFIX}"\
       --with-hunspell 
```

Error is:

```
enchant_hunspell.cpp:138:62: error: invalid conversion from
    ‘size_t*’ {aka ‘long unsigned int*’} to ‘gsize*’ {aka ‘long long unsigned int*’} 
    [-fpermissive]
  138 |  size_t result = g_iconv(m_translate_in, &in, &len_in, &out, &len_out);
      |                                                              ^~~~~~~~
      |                                                              |
      |                                                              size_t* {aka long unsigned int*}
```

Any clues?

By the way, if you find a better idea for Windows user to install enchant, I'm all ears :P

**Comment by dmerejkowsky** [comment]
_Update_: I tried with [this patch](https://github.com/pyenchant/build-enchant/blob/master/windows/0001-Fix-compilation-on-Windows-maybe.patch), but I have no clue if I'm breaking something ...

**Comment by hfiguiere** [comment]
That's what I'd suggest as a fix. Feel free to submit a pull request.

**Comment by rrthomas** [comment]
Something seems to be wrong here. From the [glib](https://developer.gnome.org/glib/stable/glib-Basic-Types.html#gsize) docs: "[gsize is] An unsigned integer type of the result of the sizeof operator, corresponding to the size_t type defined in C99." This suggests that you're building against two different sizes of `size_t`. Note that enchant is [built against hunspell](https://ci.appveyor.com/project/rrthomas/enchant) on AppVeyor, and the latest build did not error on mingw64.

**Comment by hfiguiere** [comment]
1. Here (Fedora 31 x86_64) it is `typedef unsigned long gsize;`. No mention of `size_t`. 
2. `g_iconv` expect `gsize*` as a parameter, so using anything else is bound to cause problems. This patch address that issue.
3. On Win64, `long` is 32-bits, while it is 64-bits on x86_64 which is probably another source of compatibility issues.

In short 2. is what's important here.

**Comment by rrthomas** [comment]
@hfiguiere of course it does not mention `size_t`, `gsize` is suppose to be a definition equivalent to `size_t` for platforms that do not have `size_t`. Again: `gsize` is just an alias for `size_t`. Therefore, one can use them interchangeably. And, as I said, `enchant` compiles on mingw64 without problems (you can see the build logs).

I am guessing that @dmerejkowsky is using a 32-bit libc with a 64-bit glib.

**Comment by rrthomas** [comment]
Compiling and running the following on mingw64:

    #include <stdio.h>
    #include <stddef.h>
    
    int main(void) {
        printf("size_t: %zu\n", sizeof(size_t));
        printf("unsigned long: %zu\n", sizeof(unsigned long));
        printf("unsigned long long: %zu\n", sizeof(unsigned long long));
    }

Outputs:

    size_t: 8
    unsigned long: 4
    unsigned long long: 8

So, `size_t` should be `unsigned long long` on mingw64.

Hence, closing the issue, I can't see a bug here.

**Comment by dmerejkowsky** [comment]
> I am guessing that @dmerejkowsky is using a 32-bit libc with a 64-bit glib.

I had a hunch it was a problem like this one. I'll keep digging. Thanks for the advice
