### ISSUE TITLE
abisource.com certificate expired

### ISSUE THREAD

**Issue by ineeee** [rrthomas/enchant#248]
the abisource.com website has an expired certificate (expired 5 days ago): https://www.abisource.com/projects/enchant/

got it from my package manager's `enchant` description

**Comment by hfiguiere** [comment]
it's not en enchant problem. it has been fixed.

**Comment by ineeee** [comment]
> it's not en enchant problem.

sorry, i didn't know where to post, and this was in the first paragraph in the page.

thanks!
