### ISSUE TITLE
Impossible to install enchant on MacOS using brew

### ISSUE THREAD

**Issue by JamesVanhecke** [rrthomas/enchant#258]
Python 3.8
OS: Catalyna 10.15.6

>>>brew install enchant
Error: The following formula
  [#<Dependency: "python@3.8" []>, #<Options: []>]
cannot be installed as binary package and must be built from source.
Install the Command Line Tools:
  xcode-select --install

**Comment by rrthomas** [comment]
Sorry, you'll need to file this bug against brew, not Enchant.
