### ISSUE TITLE
Bug with voikko and enchant_dict_check() with len argument != -1 (byte length of the word given)

### ISSUE THREAD

**Issue by ghost** [rrthomas/enchant#259]
See this gspell issue and my comment that comes to the conclusion that it's most probably a bug in Enchant (or Voikko).

https://gitlab.gnome.org/GNOME/gspell/-/issues/10#note_935384

Does that ring any bell?

enchant2 version 2.2.11 on Fedora 32.

I could fix the bug in gspell by allocating a new string that is nul-terminated and pass -1 to the len argument, but it would slow down a bit the execution.

**Comment by rrthomas** [comment]
Edit: I agree that enchant should take care of this. I will look into what impact that would have.

This is hilarious, as I've just today been working on a very similar documentation bug in glib: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1697

I see that the voikko assumes that the string is NUL-terminated; `voikko_dict_check` in `enchant_voikko.c` (the Voikko back-end of Enchant) ignores the `len` parameter.

**Comment by rrthomas** [comment]
This seems to affect two back-ends: Voikko and Zemberek.

**Comment by rrthomas** [comment]
> I could fix the bug in gspell by allocating a new string that is nul-terminated and pass -1 to the len argument, but it would slow down a bit the execution.

I'll have to do this anyway, since voikko does not offer an API that takes a counted string. Of course, it's better to do it in the Enchant back-end, as then it doesn't affect other libraries with more flexible APIs!

**Comment by ghost** [comment]
> Edit: I agree that enchant should take care of this. I will look into what impact that would have.

Thanks :+1: ! I'll close the gspell bug then, and once it is fixed in Enchant and there is a new release, I'll bump the version requirement of Enchant2 in gspell.

**Comment by ghost** [comment]
If doing dynamic memory allocation to nul-terminate the string degrades too much the performances (which I doubt, Enchant, Voikko etc are doing much more under-the-hood I suppose), there is still the possibility to use `alloca()` to allocate on the stack.

**Comment by rrthomas** [comment]
GCC supports `strndupa`.

**Comment by rrthomas** [comment]
Please could you have a look at the fix I've just pushed?

**Comment by rrthomas** [comment]
(N.B. I just noticed that I failed to push the final version, and have just now updated it.)

**Comment by ghost** [comment]
Not tested, but it should do its job.

An alloc can be avoided if the len is already -1. But I see that it's a `size_t` type so it's unsigned, while the one from `enchant_dict_check()` is `ssize_t` (signed).

And you use `strndup()` in one place and `g_strndup()` in another, is there a reason for that?

**Comment by rrthomas** [comment]
Indeed, it would be necessary to change the provider API to allow that optimization. Probably that could be done (I don't know of any third-party provider modules) but not worth doing unless there's a performance problem, which, as you say above, is unlikely.

One backend has already explicitly included glib.h, the other hasn't (it's included implicitly via `enchant-provider.h`). I trust glib a bit more than I trust underlying implementations to take care of details, so I'll use it where available. But really it's a bit of pedantry.

**Comment by ghost** [comment]
Now tested with gspell-app1 and voikko, the bug is indeed fixed with your Enchant commit.

Many thanks!

**Comment by rrthomas** [comment]
Thanks for confirming, I'll make a release shortly.

**Comment by rrthomas** [comment]
I have released Enchant 2.2.12

**Comment by ghost** [comment]
Thanks! :+1:

**Comment by tjyrinki** [comment]
Thank you, I've verified 2.2.12 fixes the issue!
