### ISSUE TITLE
enchant-2.2.14 test fails

### ISSUE THREAD

**Issue by ndowens** [rrthomas/enchant#266]
Here is the log out put, it is a bit long so here is a pastebin of it https://termbin.com/d1p53

**Comment by rrthomas** [comment]
Thanks, but without more information I can't do much with this (all the tests pass when I try it).

Some tracebacks would be good (from individual test log files), and also it would be good to know how Enchant is configured (in particular, with which backends).

**Comment by rrthomas** [comment]
I notice in particular you seem to be using nuspell 4.2.0. I've not yet tested with that (I'll get it when it hits the PPA). You could see what happens when you build without nuspell, or with nuspell 4.1.

**Comment by ndowens** [comment]
Figured out the issue, needed to pass --enable-relocatable and nuspell-4.2.0 was fine as well.

**Comment by rrthomas** [comment]
Good good. This is already documented.

**Comment by ndowens** [comment]
Update. Ok it passess if I do without-nuspell , 4.1.0 also gives error outout https://github.com/void-linux/void-packages/pull/27323/checks?check_run_id=1591218042

**Comment by ndowens** [comment]
How do I go about getting tracebacks?

**Comment by rrthomas** [comment]
Some error output is expected, but I guess you mean the tests don't pass?

Where tests crash, full output will be in the individual test logs. You can see `build-aux/appveyor-build.sh` for an example of how to build with ASAN, which usually gives useful backtraces.

**Comment by rrthomas** [comment]
Looking at the link you posted above, which when I first looked at it was in the middle of a build, it's currently got a build failure in the nuspell backend.

**Comment by ndowens** [comment]
> Some error output is expected, but I guess you mean the tests don't pass?
> 
> Where tests crash, full output will be in the individual test logs. You can see `build-aux/appveyor-build.sh` for an example of how to build with ASAN, which usually gives useful backtraces.

I didn't see appveyor-build.sh in build-aux

**Comment by dimztimz** [comment]
> Update. Ok it passess if I do without-nuspell , 4.1.0 also gives error outout https://github.com/void-linux/void-packages/pull/27323/checks?check_run_id=1591218042


Looking at the build log, Nuspell 4.0.0 is used. Enchant requires Nuspell v4.1.0 with a recent patch I submitted to Enchant. The best way to fix this to add in the build script of Enchant a check for minimal version. I'll open a separate issue.

**Comment by gspe** [comment]
@ndowens the problem with fail test is caused by this 2 lines in void package template
 ```
make_build_args="pkgdatadir=/usr/share/enchant-2"
make_install_args="$make_build_args"
```
without this 2 line the package compile fine without any error
