### ISSUE TITLE
 brew install --build-from-source enchant with ERROR

### ISSUE THREAD

**Issue by malizheng** [rrthomas/enchant#269]
macos 10.12.6
==> Downloading https://ftp.pcre.org/pub/pcre/pcre-8.44.tar.bz2
Already downloaded: /Users/lizhengma/Library/Caches/Homebrew/downloads/26d6d64b1dd138a02838ae49167401caeec92d83115d0822fbee5fbe50139599--pcre-8.44.tar.bz2
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/61642

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "glib--patch"
Download failed: https://raw.githubusercontent.com/Homebrew/formula-patches/6164294a75541c278f3863b111791376caa3ad26/glib/hardcoded-paths.diff

**Comment by rrthomas** [comment]
This is a brew bug not an enchant bug.
