### ISSUE TITLE
Should Aspell be preferred for English?

### ISSUE THREAD

**Issue by mavit** [rrthomas/enchant#270]
Searching online for comparisons of spellcheckers, I see it asserted that, for the English language, Aspell provides better suggestions than Hunspell.  E.g.:
- https://battlepenguin.com/tech/aspell-and-hunspell-a-tale-of-two-spell-checkers/
- http://aspell.net/test/cur/

If this is the case, would it make sense to configure the default `enchant.ordering` to prefer Aspell for English locales?

I'm happy to prepare a pull request if this seems like a good idea.

**Comment by rrthomas** [comment]
I'd be happy to accept such a pull request. In particular, Enchant is an excellent framework for making use of this sort of relative performance difference, as I guess you are thinking: users without Aspell installed will have no problem, and those who do can reap the benefits.

**Comment by juhp** [comment]
I can't help wonder if this is still a good idea in 2025, given that aspell is largely considered deprecated at this point.
It can also give unexpected results if one installs aspell "by accident".

Take for example the word "tree", for which aspell seems to produce a lot of surprising suggestions.
Maybe nuspell could make up for the speed difference?

Anyway happy to discuss in a new issue too. :-)

**Comment by rrthomas** [comment]
I don't see that anything has changed here: Aspell is still maintained, and widely available. I previously defaulted to Hunspell because it seems to be the most widely-used default, but I don't see any harm, as I said above, in picking different spell-checkers for different languages, especially when there's evidence in their favour.

I took for example the word "tree", and Aspell seems to think it's correctly spelt. But in any case, individual examples aren't very useful for this sort of decision. While Aspell is still maintained and distributed, and in the absence of better evidence that it's not a good default, I'm inclined to stick with it.

**Comment by mavit** [comment]
> aspell is largely considered deprecated at this point

Do we know why this is, by the way?  Do people simply believe that a single spell checker, in the form of Hunspell, is sufficient?

> Maybe nuspell could make up for the speed difference?

The [only performance testing I'm aware of for Nuspell](https://pyenchant.github.io/pyenchant/shootout.html) places it slowest of all three.

**Comment by juhp** [comment]
Oh that's interesting - hmm - then makes one wonder why they claim to be faster than hunspell.

**Comment by rrthomas** [comment]
> > aspell is largely considered deprecated at this point
> 
> Do we know why this is, by the way? Do people simply believe that a single spell checker, in the form of Hunspell, is sufficient?

I don't believe that aspell is deprecated. If this were a Wikipedia talk page, I'd be asking "by whom?" and suggesting "citation needed". In any case, from my perspective, principally interested in whether dependencies are widely available, there's no problem. And it's clearly maintained, with occasional new releases.

> > Maybe nuspell could make up for the speed difference?
> 
> The [only performance testing I'm aware of for Nuspell](https://pyenchant.github.io/pyenchant/shootout.html) places it slowest of all three.

This is not terribly interesting either, at least for considering default settings for most users. The speed of the back-end may or may not even be significant compared to the rest of the stack; as an extreme example, my life as an Emacs user has been much more improved by the "jinx" package, which directly links against Enchant, being much faster than using the CLI pipe-based front end, and even then, it's not been a game changer, just nice to have.
