### ISSUE TITLE
Memory leak in library entry point

### ISSUE THREAD

**Issue by jboeing** [rrthomas/enchant#277]
Running claws mail for windows with app verifier enabled caught a memory leak in `DllMain()`.  The memory allocated by

```
shared_library_fullname = strdup (location);
```

is never freed.  `_DLL_InitTerm()` looks like it has the same issue, and `find_shared_library_fullname()` seems to have a similar issue with the call to `getline()`.

The attached patch addresses the Windows case.

[free-library-name.txt](https://github.com/AbiWord/enchant/files/6927859/free-library-name.txt)

**Comment by rrthomas** [comment]
Thanks! I've removed the stylistic initialization to `NULL`, but otherwise applied it verbatim.

**Comment by rrthomas** [comment]
I'm sorry, I was in too much of a hurry! I didn't realise that you weren't actually patching enchant at all, but gnulib. You should send your bug report to bug-gnulib@gnu.org. Thanks!
