### ISSUE TITLE
enchant_dict_get_extra_word_characters() can return invalid UTF-8

### ISSUE THREAD

**Issue by chergert** [rrthomas/enchant#278]
```c
const char *enchant_dict_get_extra_word_characters (EnchantDict * dict);
```

Since the above prototype does not have a string length, it is expected to be `\0` terminated. Additionally, the documentation says that it should be valid UTF-8.

```
Returns a const char UTF-8-encoded string containing the non-letter characters
allowed in a word, e.g. "01234567890’-". If dash occurs, it will be last, so that
the string can be appended to a character class used to match word characters.
```

However, on Fedora 34, I'm seeing invalid UTF-8 coming back. What makes this worse, is that when walking the UTF-8 with GLib, you can skip past the end of the allocation boundary. So something like the following fails.

```
for (const char *c = extra_word_chars; *c; c = g_utf8_next_char (c))
  /* do something */
```

[Fedora's spec file can be found here](https://src.fedoraproject.org/rpms/enchant2/blob/rawhide/f/enchant2.spec).

For the mean time, [I've just worked around it in gnome-text-editor](https://gitlab.gnome.org/GNOME/gnome-text-editor/-/blob/9b654137cb8f86c55a1b834a0e55049c18806c2a/src/enchant/editor-enchant-spell-language.c#L213) by finding the end of the valid UTF-8 data. However, that too is brittle depending on how things get allocated.

I haven't seen the issue so far when using the `org.gnome.Sdk` Flatpak runtime, but it does not support as many backends as the Fedora RPM does so probably isn't hitting the same condition.

**Comment by rrthomas** [comment]
Thanks for filing this issue. It has to be a provider bug, so if could you could give me a provider and language combination that causes it, that would make it easier for me to track down.

**Comment by chergert** [comment]
Oh look at that, it looks like my GNOME jhbuild actually built enchant-2 so this is coming from that, not the Fedora library.

```
en_US: English (United States): hunspell Hunspell Provider /home/christian/.jhbuild/lib/enchant-2/enchant_hunspell.so
```

But as it were, I disabled that and got the same issue with Fedora anyway.

```
en_US: English (United States): hunspell Hunspell Provider /usr/lib64/enchant-2/enchant_hunspell.so
```

```
Extra Word Chars: 0123456789'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz������������������������������������������������������������
```

**Comment by rrthomas** [comment]
Thanks @chergert! I had already had a quick look at Hunspell, where indeed `get_wordchars()`, the routine that Enchant calls, indeed seems to use the same encoding as the dictionary, which is 8-bit by default; so I'll fix that first (being also the most popular back-end, I suspect).

Moreover, this is entirely my fault: I added the `enchant_dict_get_extra_word_characters` (at least I still think the design is right!).

**Comment by rrthomas** [comment]
It turns out that hunspell is the only provider that implements the underlying method, so it's the only one that needs fixing.

**Comment by rrthomas** [comment]
@chergert, please can you try the version of enchant #279? My `en_US` hunspell dictionary is UTF-8, but I was able to test it with the German dictionary, which is ISO-8859-1.

**Comment by chergert** [comment]
Yup, looks like it!

```
en_US: English (United States): hunspell Hunspell Provider /home/christian/.jhbuild/lib/enchant-2/enchant_hunspell.so
Extra: 0123456789'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþ
```

Thanks!

**Comment by rrthomas** [comment]
@chergert thanks for confirming, and thanks again for the report; I will make a new release with this fix shortly.
