### ISSUE TITLE
apt-get install enchant - 100 error code

### ISSUE THREAD

**Issue by purplecrow2020** [rrthomas/enchant#281]
my repository used to work on this docker command to deploy in one of the steps since on year  , have started to get error  in very recent , have we changed ( or is there some fix to it )

**Comment by purplecrow2020** [comment]
just to mention enchant-2 worked on mine docker container but not in the production that also vv strange, bcoz we are calling the apt-get update too

**Comment by rrthomas** [comment]
Sorry, packaging of Enchant is not done upstream; you should file an issue with the relevant distro.

**Comment by purplecrow2020** [comment]
but then just installing from the tarball also does not places dictonary in place, like i am using something of this sort - 

```
RUN wget https://github.com/AbiWord/enchant/releases/download/v2.3.1/enchant-2.3.1.tar.gz
RUN tar -xzf ./enchant-2.3.1.tar.gz
RUN cd enchant-2.3.1 && ./configure && make && make install
RUN ldconfig
```

, can u help installing enchant C from the source file itself and install en dictionaries too

**Comment by rrthomas** [comment]
It's probably best for you to get help with your distro: it should already have packages for enchant and for dictionaries. Note that Enchant itself does not provide dictionaries, or indeed the spelling checker, it is just an interface to multiple spelling checkers.
