### ISSUE TITLE
Confidence score of the suggested word

### ISSUE THREAD

**Issue by Siddhijain16** [rrthomas/enchant#283]
Hi @rrthomas 
Can we get the confidence score of the suggested word along with suggested word ? If yes how can I get it please suggest.

**Comment by rrthomas** [comment]
This is not currently possible: there's no Enchant API for this.

**Comment by rrthomas** [comment]
Closing, as Enchant no longer has its own suggestion mechanism, and provider spelling libraries do not expose confidence scores.
