### ISSUE TITLE
Enchant in Termux Android

### ISSUE THREAD

**Issue by mazhe1988** [rrthomas/enchant#286]
I don't know if I am in the right place to ask this. I am trying to use enchant in Termux. 
But when I type "enchant-2 -a somefile.txt", it return error:
@(#) International Ispell Version 3.1.20 (but really Enchant 2.3.1)
Couldn't create a dictionary for C.UTF-8
If anyone use enchant in the termux? Can help me on this issue?

**Comment by rrthomas** [comment]
Most likely you have no dictionaries installed. What does

```
enchant-lsmod-2 -list-dicts
```

say?

**Comment by mazhe1988** [comment]
thank you for reply, I have solved the problem. The enchant package from Termux repository seems like doesn’t work. I manually configure&make&make install the enchant tar ball file. It’s working now. Free to close this.

**Comment by mazhe1988** [comment]
To be clear, I do have aspell and hunspell en-US dictionary installed, but somehow the enchant package from Termux repository doesn’t configure or pointing to the dictionary properly. Manually install enchant solve the problem.

**Comment by rrthomas** [comment]
@mazhe1988 glad you were able to solve the problem; if you haven't already, please could you file a bug against the Termux package so it can be fixed for other Termux users?
