### ISSUE TITLE
enchant doesn't list en dictionaries besides hunspell-en being installed

### ISSUE THREAD

**Issue by bdaase** [rrthomas/enchant#299]
* Fedora 36
* enchant 2.3.2

I have the following hunspell dictionaries installed 

```
➜  ~ sudo dnf list installed | grep hunspell
hunspell.x86_64                                   1.7.0-17.fc36                                 @fedora
hunspell-de.noarch                                20161207-2.fc36                               @fedora
hunspell-en.noarch                                0.20140811.1-22.fc36                          @fedora
hunspell-en-GB.noarch                             0.20140811.1-22.fc36                          @fedora
hunspell-en-US.noarch                             0.20140811.1-22.fc36                          @fedora
hunspell-filesystem.x86_64                        1.7.0-17.fc36                                 @fedora
```

enchant however doesn't list the English ones

```
➜  ~ python3
Python 3.10.2 (main, Feb  1 2022, 00:00:00) [GCC 12.0.1 20220129 (Red Hat 12.0.1-0)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
>>> print(enchant.list_languages())
['de_AT', 'de_BE', 'de_CH', 'de_DE', 'de_LI', 'de_LU']
```

English seems to be the only problematic language. All other languages are listed just fine after installing their respective hunspell disctionaries.

**Comment by rrthomas** [comment]
Please file this bug against your distro in the first instance. (Happy to have an issue that uses latest enchant compiled from source with specific information about where dictionaries are installed, and not using python-enchant, as that's not part of enchant.)


I did a quick check that I can list multiple English dictionaries, so I think there's some problem with the installation in your case.

**Comment by bdaase** [comment]
Whoops, I had a typo in my initial report. It actually is 2.3.2, which is the latest version AFAICS

```
➜  ~ sudo dnf list installed | grep enchant
Place your right index finger on the fingerprint reader
enchant.x86_64                                    1:1.6.0-29.fc36                               @fedora
enchant2.x86_64                                   2.3.2-3.fc36                                  @fedora
python3-enchant.noarch                            3.2.2-2.fc36                                  @fedora
```

**Comment by rrthomas** [comment]
Sure, that is the latest version, but you're using your distro's package, so please report the bug to your distro.

**Comment by bdaase** [comment]
Alright, done. Cross-linking it here for future reference: https://bugzilla.redhat.com/show_bug.cgi?id=2058731.
