### ISSUE TITLE
Document fact that personal word list lines beginning with '#' are ignored (PWLs support comments)

### ISSUE THREAD

**Issue by kgifford-hv** [rrthomas/enchant#307]
Greetings! This is just a minor drive-by feature request. I've been googling for a while to determine if my personal word list supports command lines. I was hoping it did and manual testing seemed to work as I'd expect if lines starting with `#` were ignored. But I really wanted official documentation to confirm this to be sure.

I'm hoping I didn't just miss some mention somewhere indicating that comments were supported. If so, please forgive/ignore this.

Anyhow, I resorted to scanning the code itself and it appears from [this line](https://github.com/AbiWord/enchant/blob/823df01a92a3dad9172f0ae1a0bcfe9d7039645b/src/pwl.c#L263) in `enchant_pwl_refresh_from_file` that any line where `#` is in column 1 will be ignored (so comments _are_ supported).

If I'm correct, a mention of support for comments in personal word lists might spare some future soul the research I performed today.

For example, the `README` might have the following statement augmented: _"It is possible, and usually safe, to share Enchant’s personal word lists with other spelling checkers that use the same format (a simple plain text file with one word per line)..."_

It might be mentioned near that statement that lines starting with `#` are ignored.

Thanks!

**Comment by rrthomas** [comment]
Thanks, I'll add a note to the documentation.
