### ISSUE TITLE
Improve Travis setup: check "make distcheck" and all possible backends

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/enchant#31]
1. Travis should run "make distcheck".

2. Travis should build the ispell and zemberek backends on Ubuntu, and the ispell backend on macOS. (uspell is not available in Ubuntu or brew.)

**Comment by hfiguiere** [comment]
On MacOS:     Build Ispell backend:                   yes

On Ubuntu:    Build Ispell backend:                   yes

For Zemberek the problem is that we lookup for dbus-glib instead of dbus-glib-1. Will see about a fix for that.

**Comment by rrthomas** [comment]
Thanks very much for the fix!

**Comment by rrthomas** [comment]
It turns out not to be possible to test zemberek, because it gives an error while installing in precise or trusty on Travis.

**Comment by hfiguiere** [comment]
The problem with Zemberek detection was a regression from PR #1.

**Comment by rrthomas** [comment]
I didn't quite understand, @hfiguiere: did you mean that the problem was caused by PR #1, or that there has been a regression since PR #1?

**Comment by hfiguiere** [comment]
It is a regression introduced by PR #1. The worst part is that I commented on it and let it slide when merging. It is all good now, I just wanted to point out where it came from in case one needs to know.

**Comment by rrthomas** [comment]
Right, but although we can now build zemberek, it's not possible to test it, because installing zemberek-server fails, as I said above.
