### ISSUE TITLE
There is no tutorial to replace the spelling back end

### ISSUE THREAD

**Issue by gaonan98** [rrthomas/enchant#311]
Hello! At present, the default backend of Enchant2's spelling checker is hunsperl. I want to use aspell as my checker backend. I haven't found any related tutorials. What should I do? thank you!

**Comment by rrthomas** [comment]
This is documented in the enchant man page, under "ENCHANT ORDERING FILE".

**Comment by gaonan98** [comment]
I'm sorry I didn't find the file you were talking about. Or are you talking about [this](https://github.com/AbiWord/enchant/blob/00508d3af0948a7bc4346828b92440ea5759f9fd/src/enchant.ordering)？ What can I do to change my spell checker back end? Thank you very much!

**Comment by rrthomas** [comment]
The command "man enchant" should display documentation, that is, the man page enchant(1).

**Comment by rrthomas** [comment]
I'll add a note about the man page to the `README` file.

**Comment by rrthomas** [comment]
I have now updated the documentation to make it clearer, and also put the man pages online, accessible from the [main web page for enchant](https://abiword.github.io/enchant/).

**Comment by rrthomas** [comment]
The command "man enchant" should display documentation.

--
https://rrt.sc3d.org

**Comment by gaonan98** [comment]
Thank you!
