### ISSUE TITLE
Thanks for maintaining Enchant!

### ISSUE THREAD

**Issue by minad** [rrthomas/enchant#317]
Dear @rrthomas,

thank you for maintaining Enchant! The library is really pleasant to use. I recently made an Emacs package called [Jinx](https://github.com/minad/jinx), which is available via the [GNU ELPA](https://elpa.gnu.org/packages/jinx.html) package archive. Jinx directly binds to the native libenchant library and performs pretty well thanks to Enchant.

**Comment by rrthomas** [comment]
Good to hear from you, and Jinx looks interesting. I wrote the Enchant support for `ispell-mode` in Emacs, and I considered doing something that directly used libenchant. It's good to know that it's more performant. The reason that I didn't in the end is that keeping a separate process means that Emacs can't be crashed by a crash in the spell-checker. This seems particularly important with Enchant, where you can't in principle know what code you'll be running when you build Emacs (I mean, you can run arbitrary spelling providers).

Since this is not really an issue, I'm closing it!

**Comment by minad** [comment]
> Good to hear from you, and Jinx looks interesting. I wrote the Enchant support for ispell-mode in Emacs, and I considered doing something that directly used libenchant. 

Thanks!

> It's good to know that it's more performant.

The main advantage is that we can avoid the process communication.

> The reason that I didn't in the end is that keeping a separate process means that Emacs can't be crashed by a crash in the spell-checker.

I hope it is stable enough. It probably is since Enchant is also used directly in other programs. I have not observed crashes so far. I've got one [report](https://github.com/minad/jinx/issues/5) though, which was probably due to `enchant_dict_get_extra_word_characters` not returning UTF-8, which was fixed in Enchant 2.3.1.

**Comment by rrthomas** [comment]
> I hope it is stable enough. It probably is since Enchant is also used directly in other programs.

They are brave programs! As I say, they can control which version of Enchant they use, but they can't control which providers are used with that code. At present all the "adaptor code" I know of is shipped with Enchant itself, but that doesn't preclude bugs in the actual spell-checking libraries.

The model of a separate process seems to work quite well for LSP (Language Server Protocol) for editors; for me at least, using spell-checking mostly interactively, I don't notice any performance problems with `ispell-mode` as it is; but in any case it could be more performant even with a separate process.

Anyway, now that Jinx exists the experiments can be done, and users can decide whether they prefer in-process spell-checking. For myself, I would like to see a simplified `spell-mode` that only uses Enchant, and does not work with the older spell-checkers, all of which (except ispell itself) can be used via Enchant in any case.

**Comment by minad** [comment]
> At present all the "adaptor code" I know of is shipped with Enchant itself, but that doesn't preclude bugs in the actual spell-checking libraries.

True, but many high-profile programs link directly to Hunspell. One can reasonably assume that this backend is sufficiently stable.

> The model of a separate process seems to work quite well for LSP (Language Server Protocol) for editors; for me at least, using spell-checking mostly interactively, I don't notice any performance problems with ispell-mode as it is; but in any case it could be more performant even with a separate process.

What do you mean by mostly interactively? I assume you invoke Ispell explicitly? The idea of Jinx is to just work in the background, like the spell checkers in browsers and other programs.

> For myself, I would like to see a simplified spell-mode that only uses Enchant, and does not work with the older spell-checkers, all of which (except ispell itself) can be used via Enchant in any case.

How is that package supposed to work? Should it have an Ispell-like interface, or more like Flyspell?

You may be interested in @astoff's [jit-spell](https://github.com/astoff/jit-spell). It works like Jinx, but uses a separate process. Unfortunately I had performance problems with it, which (I suspect) are partially caused by the process communication and partially by jit-spell overeagerly spell-checking large parts of the buffer. Jinx defers all unnecessary work by only checking the visible text in the buffer. But maybe in the future Jinx and Jit-spell could converge again, such that one can either use an external process or a builtin library.

**Comment by rrthomas** [comment]
> True, but many high-profile programs link directly to Hunspell. One can reasonably assume that this backend is sufficiently stable.

Absolutely. If I were writing a program that bundled Enchant *and* its back-ends, I could choose a set of back-ends I trusted. And in general, I'd trust Hunspell. But, as the maintainer of Emacs, I can't assume that my users will use only mature providers! (You could say that the user deserves what they get for using a flaky back-end, but I don't think that's fair.)

> What do you mean by mostly interactively?

I mean that I use the `ispell` command for interactive spelling sessions where successive words are shown to me and I can correct them, rather than say batch-checking vast amounts of test, where I might like raw performance to be higher.

> I assume you invoke Ispell explicitly? The idea of Jinx is to just work in the background, like the spell checkers in browsers and other programs.

I do use flyspell too, and I don't notice it slowing things down.

> How is that package supposed to work? Should it have an Ispell-like interface, or more like Flyspell?

Just like ispell. Of course, flyspell should be able to use it. Simply not having to abstract the details of different front-ends should make the code somewhat simpler, and potentially faster.

> You may be interested in @astoff's [jit-spell](https://github.com/astoff/jit-spell). It works like Jinx, but uses a separate process. Unfortunately I had performance problems with it, which (I suspect) are partially caused by the process communication and partially by jit-spell overeagerly spell-checking large parts of the buffer. Jinx defers all unnecessary work by only checking the visible text in the buffer. But maybe in the future Jinx and Jit-spell could converge again, such that one can either use an external process or a builtin library.

Thanks for the pointer.

**Comment by minad** [comment]
> But, as the maintainer of Emacs, I can't assume that my users will use only mature providers! (You could say that the user deserves what they get for using a flaky back-end, but I don't think that's fair.)

I see your point. But note that Emacs comes with module support in the first place, so users could also decide to load other flaky native modules. So in the end there is certainly a bit of responsibility on the users themselves.

> I mean that I use the ispell command for interactive spelling sessions where successive words are shown to me and I can correct them, rather than say batch-checking vast amounts of test, where I might like raw performance to be higher.

I see. For Ispell there are of course no performance problems. It only matters when checking all the text during font locking.

> I do use flyspell too, and I don't notice it slowing things down.

I am not happy with the behavior of Flyspell to only check words at point. I prefer the spell-checking style where everything is highlighted right away. But that's of course a matter of taste. I had performance problems with Flyspell, where it lead to hanging idle timers.

> Just like ispell. Of course, flyspell should be able to use it. Simply not having to abstract the details of different front-ends should make the code somewhat simpler, and potentially faster.

Yes, hopefully. Ispell itself is a massive package and I wonder where all the complexity is coming from. It is probably a large collection of edge cases. In contrast, with Jinx or Jit-spell one avoids most of the Ispell/Flyspell-legacy and end up with a reasonably small and simple packages. I will see how well this works out in practice if users start to use Jinx in many different modes.

**Comment by rrthomas** [comment]
(Apologies, I mistakenly edited your previous comment; I've tried to undo it.)

> Yes, hopefully. Ispell itself is a massive package and I wonder where all the complexity is coming from. It is probably a large collection of edge cases.

Exactly, lots of edge cases, and a suite of functions for each of the supported spell-checking front-ends: ISpell, ASpell, Hunspell and Enchant.

**Comment by minad** [comment]
> Yes, moving to Enchant only would certainly help. I've also seen much of the complexity coming from the regexp based approaches to exclude certain regions of text.

Indeed, the ad-hoc support for various old syntaxes is not something I would preserve.
