### ISSUE TITLE
Problem finding some dictionaries

### ISSUE THREAD

**Issue by DamienCassou** [rrthomas/enchant#318]
The command `enchant-lsmod-2` returns plenty of dictionaries but not all dictionaries I have:

```
$ enchant-lsmod-2 -list-dicts
en (aspell)
en_AG (hunspell)
en_AU (aspell)
en_BS (hunspell)
en_BW (hunspell)
en_BZ (hunspell)
en_CA (aspell)
en_DK (hunspell)
en_GB (aspell)
en_GH (hunspell)
en_HK (hunspell)
en_IE (hunspell)
en_IN (hunspell)
en_JM (hunspell)
en_MW (hunspell)
en_NA (hunspell)
en_NG (hunspell)
en_NZ (hunspell)
en_PH (hunspell)
en_SG (hunspell)
en_TT (hunspell)
en_US (aspell)
en_ZA (hunspell)
en_ZM (hunspell)
en_ZW (hunspell)
fr (aspell)
fr_CH (aspell)
fr_FR (aspell)
he (hspell)
```

I can't find my French hunspell dictionaries that hunspell knows about:

```
$ hunspell -d fr-toutesvariantes -D 2>&1 | tail -n 3
LOADED DICTIONARY:
/nix/store/0frsq5f926kacxc7pxb0ga47qd4fmp38-hunspell-dict-fr-any-dicollecte-5.3/share/hunspell/fr-tout
esvariantes.aff
/nix/store/0frsq5f926kacxc7pxb0ga47qd4fmp38-hunspell-dict-fr-any-dicollecte-5.3/share/hunspell/fr-tout
esvariantes.dic
```

If I look at the system calls made by `enchant-lsmod-2`, I see that the directory `~/.nix-profile/share/hunspell` is scanned and its files are found:

```
$ strace enchant-lsmod-2 -list-dicts  2>&1 | grep .nix-profile/share
openat(AT_FDCWD, "/home/cassou/.nix-profile/share/hunspell", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
access("/home/cassou/.nix-profile/share/hunspell/en_US.aff", F_OK) = 0
access("/home/cassou/.nix-profile/share/hunspell/fr-toutesvariantes.aff", F_OK) = 0
openat(AT_FDCWD, "/home/cassou/.nix-profile/share/hunspell", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
access("/home/cassou/.nix-profile/share/hunspell/en_US.aff", F_OK) = 0
access("/home/cassou/.nix-profile/share/hunspell/fr-toutesvariantes.aff", F_OK) = 0
```

The files detected by these system calls are symlinks to the files found by the `hunspell` command above:

```
$ ls -l ~/.nix-profile/share/hunspell/
total 16
lrwxrwxrwx 1 root root 114 Jan  1  1970 en_US.aff -> /nix/store/ynvg0vv99p04955ph17vhyk1xbxr6w36-hunspell-dict-en-us-large-wordlist-2018.04.16/share/hunspell/en_US.aff
lrwxrwxrwx 1 root root 114 Jan  1  1970 en_US.dic -> /nix/store/ynvg0vv99p04955ph17vhyk1xbxr6w36-hunspell-dict-en-us-large-wordlist-2018.04.16/share/hunspell/en_US.dic
lrwxrwxrwx 1 root root 117 Jan  1  1970 fr-toutesvariantes.aff -> /nix/store/0frsq5f926kacxc7pxb0ga47qd4fmp38-hunspell-dict-fr-any-dicollecte-5.3/share/hunspell/fr-toutesvariantes.aff
lrwxrwxrwx 1 root root 117 Jan  1  1970 fr-toutesvariantes.dic -> /nix/store/0frsq5f926kacxc7pxb0ga47qd4fmp38-hunspell-dict-fr-any-dicollecte-5.3/share/hunspell/fr-toutesvariantes.dic
```

Is it possible that enchant ignores symbolic links?

**Comment by rrthomas** [comment]
I had a look at the code, and as far as I can see it follows symlinks.

I also tested it by moving some dictionary files and then symlinking them into `~/.config/enchant/hunspell`, and that worked fine too.

However, "toutesvariantes" doesn't look like a valid language tag. Indeed, when I rename a dictionary to use that as its tag, it's not found: Enchant requires dictionaries to be named with an IETF BCP 47 language tag.

I suppose an alternative would be to allow any filename, and require clients of libenchant to deal with it. This does not seem unreasonable. In this case, `enchant-lsmod` and `enchant` would work quite happily (they don't process language tags); a program such as LibreOffice that translates language tags to human-readable names would have to decide whether to ignore an invalid language, or present it without translation; but this must already be a problem that such programs have to solve when they come across a language tag they don't recognize.

**Comment by rrthomas** [comment]
Fixed by https://github.com/AbiWord/enchant/pull/335/commits/c7648ec8639128743988eb0d33465181118e7ddc

Will be released shortly.

**Comment by DamienCassou** [comment]
Thank you!
