### ISSUE TITLE
Spell checker doesn't add the properly word to the dictionary

### ISSUE THREAD

**Issue by danielgiljara** [rrthomas/enchant#331]
Hi.

I write something with spell errors and when I go to add this word to the dictionary, it shows the word splitted, not the word I typed, as attached image shows.

![Captura de pantalla de 2023-08-04 15-40-17](https://github.com/AbiWord/enchant/assets/1359101/a297acc5-0038-4fec-a80d-40f78267b173)

**Comment by rrthomas** [comment]
Sorry, I can't diagnose or fix problems in programs that use Enchant. That's not to say that the bug is not in Enchant, but I have no way of telling (although here, it doesn't seem to be a problem with Enchant). You should report the problem to the maintainers of the program you're using.

**Comment by rrthomas** [comment]
I see that you did report the bug to HexChat maintainers, and the response was that this function is implemented in libenchant. That's not actually true: libenchant is only responsible for the spelling suggestions, not for the user interface. In this case, it's not clear how the word with the letter missing is produced, and again, I can't respond to bugs in other programs. I would need a bug report showing the bug in terms of libenchant calls.

**Comment by TingPing** [comment]
The UI just calls `enchant_dict_add_to_personal`. Code largely unchanged for a long time.

**Comment by rrthomas** [comment]
Sure, but the problem is not with the addition of the word, it's with the choice of word to add, see the screenshot. The word being added is already incorrectly truncated.

**Comment by rrthomas** [comment]
A good MCVE for a libenchant bug report would be precisely "when calling `enchant_dict_add_to_personal` with this argument and an empty personal word list, the result is the following incorrect personal wordlist."

**Comment by TingPing** [comment]
> The word being added is already incorrectly truncated.


Ah you are right, sorry about that.
