### ISSUE TITLE
MacOS Homebrew install missing providers for Nuspell and others

### ISSUE THREAD

**Issue by wongandj** [rrthomas/enchant#332]
I am running MacOS Monterey.
I was trying to get enchant to recognize NuSpell (I intended to use this [hunspell-compatible academic dictionary file](https://github.com/emareg/acamedic)) when I took a look at its install directory and realized /usr/local/Cellar/enchant/2.5.0/lib/enchant-2 only has .a and .so files for applespell and aspell; I am not myself C++-savvy and compiling C gives me nightmares, but it appears to me that somehow, support for nuspell, alongside presumably hunspell, Voikko, etc. is just...missing from the homebrew package. Or, the documentation is too obtuse to figure it out :(

**Comment by rrthomas** [comment]
Please report Homebrew issues to Homebrew.
