### ISSUE TITLE
Rejected words ending in colon for sv_SE with hunspell provider

### ISSUE THREAD

**Issue by jmickelin** [rrthomas/enchant#333]
I encountered the following issue that only arises when using the Hunspell provider via Enchant and the Swedish language dictionary. Changing to a different language, a different provider, or using Hunspell directly with the Swedish dictionary does not exhibit this issue.

## Issue

Words ending in with a colon character (`:`) are marked as incorrect, regardless of whether they are spelled correctly or not.

### Using the Hunspell provider
```
$ cat ~/.config/enchant/enchant.ordering
*:hunspell,nuspell,aspell
$ enchant-lsmod-2 -list-dicts
[...]
en_GB (hunspell)
[...]
sv (aspell)
sv_FI (hunspell)
sv_SE (hunspell)
```

Behaviour with Swedish:
```
$ enchant-2 -a -d sv_SE
@(#) International Ispell Version 3.1.20 (but really Enchant 2.3.4)
apa
*

apa:
& apa: 6 0: apa, apar, apan, apat, api:, apas
```

Behaviour with English:
```
$ enchant-2 -a -d en_GB
@(#) International Ispell Version 3.1.20 (but really Enchant 2.3.4)
monkey
*

monkey:
*
```

### Running hunspell directly
```
$ hunspell -d sv_SE
Hunspell 1.7.2
apa
*

apa:
*
```

### Changing the Enchant provider to a different one: 

```
$ cat ~/.config/enchant/enchant.ordering
*:nuspell,aspell,hunspell
$ enchant-lsmod-2 -list-dicts
[...]
en_GB (hunspell)
[...]
sv (aspell)
sv_FI (nuspell)
sv_SE (nuspell)
```
(Not sure why this is still `hunspell` for `en_GB`, for what it's worth.)

This fixes the issue:
```
$ enchant-2 -a -d sv_SE
@(#) International Ispell Version 3.1.20 (but really Enchant 2.3.4)
apa
*

apa:
*
```
(Identical output for the `aspell` dictionary named `sv`.)

## Software versions
**Distro**: Fedora release 38 (Thirty Eight)
**Packages**:
- `enchant2`: `2.3.4-1.fc38`
- `enchant2-nuspell`: `2.3.4-1.fc38`
- `enchant2-aspell`: `2.3.4-1.fc38`
- `hunspell`: `1.7.2-3.fc38`
- `hunspell-sv`: `2.28-19.fc38`
- `hunspell-en`: `0.20201207-3.fc38`
- `nuspell`:  `5.1.2-4.fc38`
- `aspell`: `12:0.60.8-11.fc38`
- `aspell-sv`: `50:0.51-28.fc38`

(I believe the Hunspell provider comes bundled with the `enchant2` package.)

## Theory

Swedish does sometimes permit a colon character in the middle of words, namely for acronyms (where the colon goes between the acronym and the grammatical word ending). It appears `enchant-hunspell` is actually treating these sort of correct. It fails to recognize the root word or identify compound words, however. (Meanwhile, instead `enchant-nuspell` does the wrong thing, treating the colon as a separator between two words regardless of whether the ending is a grammatical suffix or not. This does, however, be an issue with Nuspell itself, since it exhibits the same problem.)

Here is what Hunspell thinks:
```
$ hunspell -d sv_SE
Hunspell 1.7.2
DVD
*

DVD:
*

DVD:er
+ DVD:

DVD:n
+ DVD:

DVD:asdfgh 
# DVD:asdfgh 0

DVD-film
-

DVD:VHS
-

DVD:USA
# DVD:USA 0
```
The last two demonstrate compound words, one which ostensibly exists according to Hunspell (whatever a DVD-VHS could be; it accepts it both when using a colon or a hyphen) and the second one does not.

Compare this to `enchant-hunspell`:
```
$ enchant-2 -a -d sv_SE
@(#) International Ispell Version 3.1.20 (but really Enchant 2.3.4)
DVD 
*

DVD:
*

DVD:er
*

DVD:n
*

DVD:asdfgh
# DVD:asdfgh 0

DVD-film
*

DVD:VHS
*

DVD:USA
# DVD:USA 0
```

For reference, here is what Hunspell does for incorrect acronyms:
```
$ hunspell -d sv_SE
Hunspell 1.7.2
KTHXBAIBBQ
# KTHXBAIBBQ 0

KTHXBAIBBQ:ar
# KTHXBAIBBQ:ar 0

KTHXBAIBBQ:DVD
# KTHXBAIBBQ:DVD 0
```

**Comment by jmickelin** [comment]
Oops, I accidentally posted the wrong output for Enchant in the *Theory* section (`enchant-nuspell` insead of the intended `enchant-hunspell`). Fixed it now.

**Comment by rrthomas** [comment]
libhunspell only has a notion of "characters valid in a word" (while Enchant has a notion of characters valid at the start, in the middle and at the end of a word). So, a colon is allowed in Swedish, but with the colon the word is mis-spelled.

Hunspell's front-end has more sophisticated parsing abilities, but Enchant does not have access to these, as it only uses libhunspell. The dictionaries themselves only say what are valid word characters.

So, sorry! There's not a lot to be done here, other than use a program that does better word detection than `enchant` is able to do. (Enchant aims to have minimal intelligence built in, while using as much information as it can from the spelling provider. In this case, not much info is available. I do not plan to make Enchant more sophisticated except where this is possible with APIs provided by, ideally, multiple providers. Note that the main use case for the front-end is with a program such as Emacs that does its own word detection.)

**Comment by jmickelin** [comment]
Ah, okay. That makes sense. Sounds like it isn't realistic to expect a common API to be created any time soon. At least I found a workaround by switching providers to e.g. `nuspell`.

My main use is actually Emacs with the [jinx](https://github.com/minad/jinx) package. I guess i should create a ticket for that project instead! So the idea is to strip out e.g. punctuation at the ends of words and send that to Enchant? (Or perhaps both check the word as-written and with the punctuation stripped and see if either is correct, to rule out false negatives :shrug: )

**Comment by rrthomas** [comment]
Various heuristics are possible. Obviously what one really wants is better language-specific knowledge about what constitutes a word…
