### ISSUE TITLE
Confusion regarding en-GB-ize (and language variants)

### ISSUE THREAD

**Issue by haji-ali** [rrthomas/enchant#334]
As far as I understand, the `en-GB-ize` dictionary should accept and suggest words ending with -ize instead of -ise, but this doesn't seem to work in enchant.

```
> enchant-lsmod-2 -lang en_GB-ize
en_GB_IZE (aspell)

> echo "categorize authorize randomize" > /tmp/test
> enchant-2 -l -d en_GB-ize /tmp/test
categorize
authorize
randomize

> enchant-2 -v    
@(#) International Ispell Version 3.1.20 (but really Enchant 2.5.0)
```

Note that aspell works as expected (see [here](https://github.com/GNUAspell/aspell/issues/638#issuecomment-1732445220) too):
```
> echo "categorize authorize randomize" | aspell -a -d en_GB-ize
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.8)
*
*
*
```

Is selecting a language variant possible in enchant?

**Comment by rrthomas** [comment]
[Apologies if you got earlier versions of this comment; I failed to spot my own command typo.]

Enchant indeed doesn't currently support language variants. See #318.

**Comment by rrthomas** [comment]
However, the `enchant-2` command runs fine, just as you show. I don't understand why the language tag is not rejected in that case. I will do some digging. In any case, as you can see from #318, I would like to end up accepting any old language tag.

**Comment by rrthomas** [comment]
Ah, it transpires that `en_GB_IZE` is a valid tag, and `enchant-2` is normalizing the given tag to that, but `enchant-lsmod-2` is not, it seems.

**Comment by haji-ali** [comment]
@rrthomas, I see. I guess I was thrown off by the fact that `enchant-lsmod-2 -lang en_GB-ize` returns a dictionary.

Is this a planned feature? Looking at the [source code](https://github.com/AbiWord/enchant/blob/e9f26cd448f3d95234336b269c70a6d1652259bf/providers/enchant_aspell.c#L117C40-L117C48), It seems that, for aspell at least, it's as simple as setting the `variety` option based on the `tag`. See [here](http://aspell.net/man-html/How-Aspell-Selects-an-Appropriate-Dictionary.html).

Happy to contribute a pull-request if that's a planned feature.

**Comment by haji-ali** [comment]
Even simplier, according to aspell's [options](http://aspell.net/man-html/The-Options.html), selecting variants would work if `master` is used to select dictionaries instead of (or maybe in addition) to `language-tag`.

**Comment by rrthomas** [comment]
I'd be delighted to get a PR for this. For your case, it should just be a case of parsing the variant out of the tag, as you say. For other providers, I'm not sure, but I think #318 is a different case, because there `toutesvariantes` is not in the position of the variant, but of the language (and in any case, we're dealing with hunspell, not aspell there).

**Comment by rrthomas** [comment]
Just a heads-up: I am about to merge recent code clean-up, plus, as I suggested in #318, the removal of language tag validation.

**Comment by rrthomas** [comment]
Closed by upcoming release. Many thanks for your contribution!
