### ISSUE TITLE
AttributeError: module 'enchant' has no attribute 'Dict'

### ISSUE THREAD

**Issue by Elie60** [rrthomas/enchant#341]
I get this issue when I want to set a language.

```
# import enchant as EC
# help(enchant)
# ddd = EC.Dict("en_US"
from enchant.checker import SpellChecker
chkr = SpellChecker("en_US")
```

**Comment by rrthomas** [comment]
This is a pyenchant issue; please report it to pyenchant. Also, the above does not actually show what your issue is; you may want to make it clearer!
