### ISSUE TITLE
Purpose of the .exc file

### ISSUE THREAD

**Issue by doolio** [rrthomas/enchant#342]
Under `~/.config/enchant/` I have two files namely `en_GB.dic` and `en_GB.exc`. Entries to my personal dictionary end up in `en_GB.dic` but so far `en_GB.exc` remains empty. What is the purpose of this .exc file? I keep my en_GB.dic file under version control to share between machines should I also include this .exc file as well?

**Comment by rrthomas** [comment]
This file records exclusions, that is, words that are in the dictionary that the user considers to be incorrect or otherwise undesired. These words will be considered incorrect by Enchant.

Thanks for bringing this to my attention; I'll add documentation about this.

**Comment by rrthomas** [comment]
I'll release 2.6.2 shortly with this documentation fix. Thanks again!
