### ISSUE TITLE
Enchant not finding hunspell on macOS

### ISSUE THREAD

**Issue by ashton314** [rrthomas/enchant#348]
I just upgraded to enchant 2.6.4 from 2.6.3 and it broke. :/ Not exactly sure why.

When I run `enchant-lsmod-2` I get:
```
aspell (Aspell Provider)
AppleSpell (AppleSpell Provider)
```

but I have hunspell installed, and I'd like to use that. I have ordering set up:

```
➤ ~ cat ~/.config/enchant/enchant.ordering
*:hunspell,AppleSpell,aspell
```

And here's the debug:
<details>
<summary><pre>env G_MESSAGES_DEBUG=libenchant enchant-lsmod-2 -list-dicts</pre></summary>
<pre>
(process:19564): libenchant-DEBUG: 18:04:20.819: reading ordering file /Users/ashton/.config/enchant/enchant.ordering
(process:19564): libenchant-DEBUG: 18:04:20.821: enchant_broker_list_dicts
(process:19564): libenchant-DEBUG: 18:04:20.821: provider Aspell Provider
(process:19564): libenchant-DEBUG: 18:04:20.824: tag af
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag am
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag ar
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag ast
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag az
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag be
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag be_BY
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag be_SU
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag bg
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag bn
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag br
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag ca
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag ca
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag ca
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag cs
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag csb
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag cy
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag da
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag de
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag de
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag de_AT
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag de_CH
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag de_DE
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag el
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_AU
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_AU
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_AU
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_AU
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_AU
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_CA
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_CA
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_CA
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_CA
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_CA
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_GB
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_GB
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_GB
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_GB
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_GB
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_GB
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_GB
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_GB
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_GB
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_GB
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_GB
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_US
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_US
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_US
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_US
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag en_US
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag eo
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag es
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag et
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag fa
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.824: tag fa
(process:19564): libenchant-DEBUG: 18:04:20.824: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fa
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fa
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fi
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fo
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr_CH
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr_CH
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr_CH
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr_CH
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr_CH
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr_CH
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr_CH
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr_FR
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr_FR
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr_FR
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr_FR
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr_FR
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr_FR
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fr_FR
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag fy
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag ga
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag gd
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag gl
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag gl
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag gr
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag grc
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag gu
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag gv
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag he
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag hi
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag hil
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag hr
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag hsb
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag hu
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag hus
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag hy
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag ia
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag id
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag it
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag kn
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag ku
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag ky
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag la
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag lt
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag lv
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag mg
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag mi
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag mk
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag ml
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag mn
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag mr
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag ms
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag mt
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag nds
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag nl
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag nn
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag ny
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag or
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag pa
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag pl
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag pt_BR
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.825: tag pt_PT
(process:19564): libenchant-DEBUG: 18:04:20.825: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag qu
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag ro
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag ro
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag ru
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag ru
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag ru
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag ru
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag rw
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag sc
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag sk
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag sk_SK
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag sl
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag sr
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag sr
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag sr
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag srd
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag sv
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag sw
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag ta
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag te
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag tet
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag tk
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag tl
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag tn
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag tr
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag uk
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag uz
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag vi
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag wa
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag yi
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: tag zu
(process:19564): libenchant-DEBUG: 18:04:20.826: priority 1
(process:19564): libenchant-DEBUG: 18:04:20.826: provider AppleSpell Provider
af (aspell)
am (aspell)
ar (aspell)
ast (aspell)
az (aspell)
be (aspell)
be_BY (aspell)
be_SU (aspell)
bg (aspell)
bn (aspell)
br (aspell)
ca (aspell)
cs (aspell)
csb (aspell)
cy (aspell)
da (aspell)
de (aspell)
de_AT (aspell)
de_CH (aspell)
de_DE (aspell)
el (aspell)
en (aspell)
en_AU (aspell)
en_CA (aspell)
en_GB (aspell)
en_US (aspell)
eo (aspell)
es (aspell)
et (aspell)
fa (aspell)
fi (aspell)
fo (aspell)
fr (aspell)
fr_CH (aspell)
fr_FR (aspell)
fy (aspell)
ga (aspell)
gd (aspell)
gl (aspell)
gr (aspell)
grc (aspell)
gu (aspell)
gv (aspell)
he (aspell)
hi (aspell)
hil (aspell)
hr (aspell)
hsb (aspell)
hu (aspell)
hus (aspell)
hy (aspell)
ia (aspell)
id (aspell)
it (aspell)
kn (aspell)
ku (aspell)
ky (aspell)
la (aspell)
lt (aspell)
lv (aspell)
mg (aspell)
mi (aspell)
mk (aspell)
ml (aspell)
mn (aspell)
mr (aspell)
ms (aspell)
mt (aspell)
nds (aspell)
nl (aspell)
nn (aspell)
ny (aspell)
or (aspell)
pa (aspell)
pl (aspell)
pt_BR (aspell)
pt_PT (aspell)
qu (aspell)
ro (aspell)
ru (aspell)
rw (aspell)
sc (aspell)
sk (aspell)
sk_SK (aspell)
sl (aspell)
sr (aspell)
srd (aspell)
sv (aspell)
sw (aspell)
ta (aspell)
te (aspell)
tet (aspell)
tk (aspell)
tl (aspell)
tn (aspell)
tr (aspell)
uk (aspell)
uz (aspell)
vi (aspell)
wa (aspell)
yi (aspell)
zu (aspell)
</pre>
</details>

Hunspell is working when I invoke it on the command line:

```
➤ ~ hunspell
Hunspell 1.7.2
blarg
& blarg 2 0: blag, blare
```

Why isn't Enchant finding hunspell? Happy to provide more details if you need them.

OS: macOS 14.2
shell: zsh

**Comment by ashton314** [comment]
This might be a problem with something homebrew is doing… I just installed 2.6.3 from the release tarball and now everything is working again.

**Comment by rrthomas** [comment]
I can't think of any change between 2.6.3 and 2.6.4 that would cause this; what happens if you install 2.6.4 from the release tarball?

**Comment by ashton314** [comment]
Huh, I upgraded and can't reproduce. Must be something with the homebrew install process. 🤷🏼‍♂️ Sorry to trouble you!

**Comment by rrthomas** [comment]
Thanks for confirming and closing!
