### ISSUE TITLE
Build option to choose to build documentation or not

### ISSUE THREAD

**Issue by franko** [rrthomas/enchant#353]
Currently, after the ./configure way invoked the Makefile will attempt to build the documentation using groff. In some case people may want to opt out from building documentation.

It would be possible to add a configure option to choose not to build the documentation ?

**Comment by rrthomas** [comment]
Users who don't want to build the docs can use a more specific make target.

**Comment by franko** [comment]
Thank you @rrthomas that's very helpful.

Can I take the opportunity to ask what's the purpose of the gnulib for this project ? I have seen some comment about its usage for the relocatable option but I would be more confident to have the explanations from you if possible.

**Comment by rrthomas** [comment]
The main way to understand what gnulib is used for in a project is to look at the value of `gnulib_modules` in `bootstrap.conf`.

In enchant, it's used for a mixture of things: the APIs `flock` and `strchrnul` (neither is a standard POSIX API), the former is needed and the latter useful; `relocatable-lib-lgpl`, a fairly complex module which makes libenchant relocatable, and the modules `bootstrap` (a different version of gnulib bootstrap which I use), `gnu-make` (test whether `make` is GNU Make, as some features of the build system require GNU Make), `manywarnings` (turn on many C/C++ compiler warnings) and `configmake` (allow `configure` variables to be automatically propagated to Makefiles).

Most of these facilities are no big deal, and would be easy to replace in another build system; the tricky one is `relocatable-lib-lgpl`.

**Comment by franko** [comment]
Thank you for the explanations, that's very useful, I appreciate.

I see about the relocation functions and how this is important for enchant. However, if I understand correctly, the relocation relies on the location of the shared library so it will works only when enchant is compiled as a shared library but I am not completely sure.

Otherwise, about flock, compiling the project on macOS using ./configure --enable-relocatable and enabling only nuspell I see flock.c doesn't actually gets compiled. I guess this is because I am compiling on macOS and flock functions are not available but I would look more closely. I will do also more tests on Linux.

I am wondering if the enchant library use an alternative mechanism on operating systems where flock is not supported.

**Comment by rrthomas** [comment]
Indeed, relocation depends on Enchant being compiled as a shared library. Enchant is almost always compiled as a shared library.

flock: the beauty of gnulib is that I delegate to it. What happens on different platforms depends on gnulib. You can see what the platform support is by looking at the source code of the gnulib flock module, starting with `gnulib/modules/flock`. In particular, you'll find that there's Windows support, and other platforms are assumed to have flock. I suspect the build will fail on other platforms that lack flock, but I don't know. I've never had a bug report about it.
