### ISSUE TITLE
assertion failed error with enchant-2.6.6 and evolution mail client

### ISSUE THREAD

**Issue by fskmh** [rrthomas/enchant#356]
Evolution segfaults with this error after upgrading from enchant-2.6.5 to 2.6.6:
`GLib-WARNING **: 12:45:41.441: GError set over the top of a previous GError or uninitialized memory.
This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
The overwriting error message was: Error opening directory “/home/user/.config/enchant/hunspell”: No such file or directory`

If I create the missing directory hunspell, I get the following error when starting up evolution:
`ERROR:enchant_hunspell.cpp:300:char* hunspell_request_dictionary(const char*): assertion failed: ((dir == NULL && err != NULL) || (dir != NULL && err == NULL))
Bail out! ERROR:enchant_hunspell.cpp:300:char* hunspell_request_dictionary(const char*): assertion failed: ((dir == NULL && err != NULL) || (dir != NULL && err == NULL))
Aborted`

If I downgrade to enchant-2.6.5, evolution starts up fine. The problem seems to be caused by this commit:
https://github.com/AbiWord/enchant/commit/56d9a10557aa732c1b875261c91de31253ab4d12

**Comment by rrthomas** [comment]
Many thanks for the report and analysis, and apologies for the bug. I will try to get a fix release out later today.

**Comment by rrthomas** [comment]
I've released 2.6.7 now. Apologies for the bug again, and thanks for the fix!
