### ISSUE TITLE
Mention vala rewrite in README

### ISSUE THREAD

**Issue by ryandesign** [rrthomas/enchant#366]
I understand from the 2.7.0 release notes that enchant has been rewritten in vala but the README still says it is written in C and C++:

https://github.com/AbiWord/enchant/blob/3a3e9df6306012bd01877621e99dda05f38841d7/README#L28

**Comment by rrthomas** [comment]
Fixed in rrthomas/master, will be merged and released shortly. Thanks for the issue!
