### ISSUE TITLE
Lack of clarity about `enchant-lsmod`

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/enchant#382]
@david-vicente asks: "Is enchant-lsmod-2 supposed to show all the available dictionaries by provider, or the dictionaries in use and their assigned providers (i.e. listing the assignments forced by enchant.ordering )? Additionally, if the former is the correct one, is there a way of knowing which provider is being used when we run enchant-2?"

**Comment by david-vicente** [comment]
Thank you. Maybe I should add that the first question is an `enchant-lsmod` question, but the second seems to be more of an `enchant` question, don't you think?

**Comment by rrthomas** [comment]
I think the answer to the first question is clearly the latter (from the enchant-lsmod-2 man page). That obviates your second question. Closing the issue, but feel free to reopen with more detail if you find the docs unclear.
