### ISSUE TITLE
High CPU usage/slowdowns with Enchant 2.8

### ISSUE THREAD

**Issue by emacsomancer** [rrthomas/enchant#386]
I'm using Enchant via [jinx.el](https://github.com/minad/jinx/). Everything has been working smoothly until Enchant 2.8, after which point I'm getting massive slowdowns and high cpu usage. The problem arose in a period where nothing significant had changed with jinx, and I've talked to the jinx developer (see https://github.com/minad/jinx/discussions/180) and they point to the 'check' call in Enchant itself suddenly seeming very expensive.

**Comment by rrthomas** [comment]
Apologies, I am pretty sure I know what caused this: I removed an optimization which made no difference to the tests, but I suspect it matters in real-world use. As a quick test, you could try temporarily deleting or emptying your personal wordlist and seeing if that helps.

In any case, I will restore the optimization, and make a release soon.

**Comment by emacsomancer** [comment]
Can I do that simply by removing/renaming ~/.config/enchant ?

[Yes, as far as I can tell, this seems to have improved things.]

**Comment by rrthomas** [comment]
Yes, that would do it!

**Comment by rrthomas** [comment]
Ah, many thanks for the confirmation. Out of interest, how large is your personal wordlist? I would like to know whether I should have found this problem myself!

I shall release 2.8.1 with the optimization restored shortly.

**Comment by rrthomas** [comment]
2.8.1 released with optimization restored.

**Comment by emacsomancer** [comment]
> Ah, many thanks for the confirmation. Out of interest, how large is your personal wordlist? I would like to know whether I should have found this problem myself!
> 
> I shall release 2.8.1 with the optimization restored shortly.

Was trying some more testing and it may be indeed when there are large wordlists in the ~/.config/enchant directory. It seems like on my one machine there was a large dictionary file in there and I *think* that may have been the issue (but it didn't seem to be on pre 2.8.0 releases, or at least, not obviously so).

**Comment by rrthomas** [comment]
Indeed, large PWLs should have been fine on previous releases, and should now be OK again.
