### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by osevan** [rrthomas/enchant#387]
I did ./bootstrap

And ./configure  flag like in HACKING described
Content of config.log and make.log
https://www.file-upload.net/download-15345414/enchant.tar.xz.html

**Comment by osevan** [comment]
I want compile enchant with different libc pkg,. 


Please tell me which pkg i need exactly.
Because groff pkg content is huge.

I dont need all

**Comment by rrthomas** [comment]
As you observe, you'll need to install groff. I don't think there's an issue here.

**Comment by osevan** [comment]
https://file.io/XNkU7KyFVdnK
