### ISSUE TITLE
bootstrap gnulib domain down

### ISSUE THREAD

**Issue by osevan** [rrthomas/enchant#390]
/bootstrap
bootstrap: warning: Consider installing git-merge-changelog from gnulib.
bootstrap: running: /usr/bin/libtoolize --quiet
bootstrap: running: git clone 'https://git.savannah.gnu.org/git/gnulib.git' 'gnulib'
Cloning into 'gnulib'...
fatal: unable to access 'https://git.savannah.gnu.org/git/gnulib.git/': Failed to connect to git.savannah.gnu.org port 443 after 133717 ms: Could not connect to server

Thanks and

Best regards

**Comment by rrthomas** [comment]
Thanks for the report, I can confirm, and I'll investigate further if it doesn't come back soon.

**Comment by rrthomas** [comment]
Appears to be OK now.
