### ISSUE TITLE
Fix all warnings

### ISSUE THREAD

**Issue by PanderOpenTaal** [rrthomas/enchant#4]
Fix all warnings:
- variable '...' set but not used [-Wunused-but-set-variable]
- warning: passing argument ... of '...' from incompatible pointer type [-Wincompatible-pointer-types]
- note: expected 'const char \* const\* const' but argument is of type 'char **'
- note: expected 'const char *_' but argument is of type 'char *_'
- warning: return discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers] WITH note: in expansion of macro '...'

The latter could result in a change in the API and communication and relase to API users needs te be coordinated.

**Comment by rrthomas** [comment]
I believe this issue can now be closed, as all the warnings mentioned are either fixed, or are addressed by outstanding pull requests. Thanks, @PanderOpenTaal!

**Comment by hfiguiere** [comment]
See PR #19 #20 #21
