### ISSUE TITLE
Is it intended that the HTML manpages get installed to docdir?

### ISSUE THREAD

**Issue by aleasto** [rrthomas/enchant#400]
I'm updating the enchant-2 package for debian/ubuntu and the HTML manpages files showed up in `$docdir`.

Was that intended? I thought the purpose of the HTML manpages would be to be browsed online, and not installed on the system.

Would also be nice to avoid groff as a mandatory build dependency.

**Comment by rrthomas** [comment]
This is intended; some people may prefer to view HTML on their system, e.g. using Debian's docbase infrastructure, or simply find it better than man pages.
