### ISSUE TITLE
Reference counting change of dictionary objects

### ISSUE THREAD

**Issue by minad** [rrthomas/enchant#402]
I noticed the following change in the NEWS file.

> There is a small change to the semantics of dictionaries: in the past,
requesting a dictionary with the same language tag twice from a given
provider returned the same dictionary object. This is no longer the case.
This allows an application to have multiple active spelling sessions with
the same broker object in any given language. Applications that relied on
this functionality must in future keep track of the identity of spelling
sessions themselves. I do not regard this as an API/ABI change, since it was
only documented in a vague way by saying that dictionaries were
“reference-counted”. This language has been removed from the documentation.

FWIW In Jinx I relied on the reference counting behavior, and on this specific part of the documentation. Now Jinx creates unnecessary dictionary objects, one for each buffer, even if the language tag is the same in most buffers. It is also not trivial to implement the reference counting myself since then I have to keep track of the shared dictionary objects across buffers. Is there a chance to restore the reference counting? (EDIT: For now I simply retain all the dictionaries in jinx--dicts-alist. Maybe I could also use some kind of weak hash table.)

If possible I hope that "subtle" changes or "not even API" changes can be avoided in the future.

Thank you!

**Comment by minad** [comment]
I switched over to a weak hash table, which works well: https://github.com/minad/jinx/commit/ad83530549e55027a3eed3f0a6239ca06f097abd

**Comment by rrthomas** [comment]
I apologise for the inconvenience. The only changes I now have in mind (other than bug fixes) involve a major version bump, as previously discussed, but my focus when I next find time for Enchant will be to continue stabilising the 2.8.x series, which, aside from this issue, has others (as you and others have noted).

**Comment by minad** [comment]
Okay, thanks. It is not a problem to use a weak hash table in Jinx for the loaded dictionaries.
