### ISSUE TITLE
Remove enchant_fopen

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/enchant#42]
enchant_fopen was added "so that Enchant and Glib don't necessarily have to be built against the same C runtime" according to Dom's commit log.

This sounds like a bad idea to me, because it's too easy to break elsewhere in the code. I believe the correct approach is to use only glib functions, so that (in this case), the same `FILE *` is always used.

Have I overlooked something?

**Comment by rrthomas** [comment]
The Windows build instructions in `Build.win32.readme` say explicitly "This means you need to compile glib and libintl yourself". Unless this remark is no longer true (for example, because of `enchant_fopen`), then it seems that `enchant_fopen` does not solve the problem anyway.

**Comment by TingPing** [comment]
+1 to removal. Mixing runtimes isn't supported by anybody and is doomed to fail so enchant shouldn't pretend it is an acceptable solution.

The most popular binary releases on Windows such as MSYS2 and wingtk even package enchant anyway so most developers shouldn't be worrying about mixing binaries from different sources built against different runtimes.

**Comment by rrthomas** [comment]
Removed on rrthomas/enchant-2-0, so will be in next release (it's an API change for providers).
