### ISSUE TITLE
Annoying warning in enchant++.h

### ISSUE THREAD

**Issue by JMLas** [rrthomas/enchant#5]
We support enchant in LyX and compilation gives this warning with clang:

```
In file included from ../../master/src/EnchantChecker.cpp:14:
/usr/include/enchant/enchant++.h:55:25: warning: 'enchant::Exception::what'
      hides overloaded virtual function [-Woverloaded-virtual]
                        virtual const char * what () throw() {
                                             ^
/usr/include/c++/v1/exception:95:25: note: hidden overloaded virtual
      function 'std::exception::what' declared here: different qualifiers
      (const vs none)
    virtual const char* what() const _NOEXCEPT;
                        ^
```

A trivial fix is be to make the 'what()' method const. I can provide a patch but I am not sure it is worth the hassle.

**Comment by hfiguiere** [comment]
this would break API/ABI, sadly.

**Comment by JMLas** [comment]
OK, I guess we have it live with it :)

What about adding a second version?

**Comment by rrthomas** [comment]
@JMLas, could you check my enchant-2-0 [branch](/rrthomas/enchant/tree/enchant-2-0) to see if I've done this right?

**Comment by JMLas** [comment]
This is what I would have done, does not mean that it is 100% correct ;)

I see that in C++11 the method is now annotated noexcept instread of throw(), but this might be equivalent.

**Comment by rrthomas** [comment]
Thanks. I'm not a C++ expert, so I'm really relying on others to get this right! According to e.g. http://stackoverflow.com/questions/12833241/difference-between-c03-throw-specifier-c11-noexcept it seems that `throw()` is deprecated (but equivalent in this case), and it would seem reasonable to use `noexcept` in a new API.

Does that sound reasonable?

**Comment by hfiguiere** [comment]
Removing the `throw()` specifiers should be all it takes. Technically it break API though, be aware of this.

**Comment by rrthomas** [comment]
@hfiguiere, what's the tradeoff between removing `throw()` and adding `noexcept`? Presumably the latter gives more (useful) information?

I understand it's a change to the API, which is why this is on my enchant-2-0 branch.

**Comment by JMLas** [comment]
Concerning the API change, I do not see how it can break any code at source level. It is an ABI change, though. But since the virtual override is incorrect, I'd say that the current definition is useless.

**Comment by rrthomas** [comment]
@JMLas, could you possibly make a concrete suggestion for a change, please? I'm not confident I understand the implications of your remark above.

**Comment by hfiguiere** [comment]
Given the class is inline it should be ok (my bad, there is no ABI here). Also changing from `throw()` to nothing is fine. This is mostly a no-op anyway, so indeed, even though technical API change, it will be harmless. 

Submitting PR.

**Comment by JMLas** [comment]
Looks like travis disagrees with removing the throw()... But I would still appreciate to add the "const" :)

**Comment by hfiguiere** [comment]
urgh. Updating the PR over there. Not sure why I didn't catch this here.

**Comment by hfiguiere** [comment]
Travis is green now.

**Comment by JMLas** [comment]
Thanks.

**Comment by rrthomas** [comment]
@JMLas, if you'd like to look at my enchant-2-0 branch, I've added a patch there: https://github.com/rrthomas/enchant/tree/enchant-2-0

I'm closing this bug; of course feel free to reopen if it seems not to be fixed.
