### ISSUE TITLE
Remove binary relocation support

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/enchant#51]
This is not actually used, except in one minor way by the unit tests.

Remove this use, and then remove the binary relocation code.

**Comment by TingPing** [comment]
Enchant does need to be relocatable though, I haven't taken a great look at what the binreloc option really does though.

On windows it should be using `g_win32_get_package_installation_directory_of_module()` and that solves that.

On Unix it should probably just support env vars for the libdir or prefix, this is required for bundles such as Snap and OSX.

In the past I've been using this patch: https://gist.github.com/TingPing/2d88a875b50da15c352d#file-enchant-prefix-patch

**Comment by rrthomas** [comment]
Closed by PR #63.
