### ISSUE TITLE
enchant_get_version() should return const char*

### ISSUE THREAD

**Issue by hfiguiere** [rrthomas/enchant#6]
enchant_get_version() should return const char*

This will break API/ABI.

**Comment by rrthomas** [comment]
I suggest that it is not too soon for a new enchant release that makes some breaking API/ABI changes, especially if the aim is simply to fix some minor problems.

I made a [branch](/rrthomas/enchant/tree/enchant-2-0) for this, and fixed the remaining const-ness warnings, for this issue, for issue #5 and issue #4, and for another warning that came up. It also removes the deprecated APIs (I think 10 years of deprecation is enough). According to the rules in `configure.in`, it is numbered 2.0.0.

**Comment by rrthomas** [comment]
@hfiguiere, if you can open an enchant-2-0 branch, I can open a pull request on it. Or of course you might not agree with my suggestion that it's time to consider a new release!

**Comment by hfiguiere** [comment]
I actually would prefer a 1.6.x branch and have the rest merged with master.

**Comment by rrthomas** [comment]
That's fine, all my pull requests so far are suitable for 1.6.x, so if you accept them (or indicate which ones you don't want), then you can branch 1.6.x, and the rest can go on master.

**Comment by rrthomas** [comment]
Closing; fixed in `enchant-2-0` branch at https://github.com/rrthomas/enchant/tree/enchant-2-0
