### ISSUE TITLE
Ready for 1.6.1?

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/enchant#69]
As far as I'm concerned, 1.6.1 is ready to release.

@hfiguiere and @TingPing, please comment if there's anything that seems to be missing (or that shouldn't be there). Otherwise, I will plan to release around 12:00 GMT on Monday 6th February.

The intention is that 1.6.1 has three main focuses:

1. Improved `enchant-ispell`.
2. Reactivated unit tests.
3. Clean-up.

In addition there are some bug-fixes such as the way words are added to PWLs (issue #24), which don't affect the API/ABI.

**Comment by TingPing** [comment]
Unittests fail on Arch because it has a custom pkgconfig file for unittest++ (and the package is unmaintained so probably won't be fixed anytime soon). I can make a PR to workaround that.

**Comment by rrthomas** [comment]
Thanks, that would be good. I guess it's different from both upstream and Debian, then?

**Comment by rrthomas** [comment]
@hfiguiere, please could you delete the releases `enchant-1-6-1`, `release-2-2-0`, `release-2-2-1` and `release-2-2-2`? None of these seem to relate to actual public releases.

**Comment by hfiguiere** [comment]
`release-2-2-*` are AbiWord releases.... they are gone. Otherwise 1-6-1 was never released. So deleted it too. These came straight out of SVN.

**Comment by rrthomas** [comment]
@hfiguiere Am I missing something? I still see these on GitHub at https://github.com/AbiWord/enchant/releases

**Comment by rrthomas** [comment]
Ping @hfiguiere: the AbiWord release tags & 1.6.1 tag still seem to be there on `AbiWord/enchant`.

**Comment by rrthomas** [comment]
Release update: it occurred to me to look into Windows CI. I have fixed the tests under MSYS, and am working on AppVeyor CI, so we can have some confidence in the release on Windows.

**Comment by hfiguiere** [comment]
I didn't realise I had to delete the release manually. I just did. Sorry about that.

**Comment by rrthomas** [comment]
Thanks!

**Comment by rrthomas** [comment]
I've made the release.

If(!) problems develop, we can decide whether it's worth having a 1.6.x maintenance branch. Otherwise, I plan to push forward with the 2.0 improvements and changes.

**Comment by TingPing** [comment]
For future release can you change the tags to be `x.y.z` rather than `x-y-z` as it better integrates with various tools.

**Comment by rrthomas** [comment]
On 8 February 2017 at 23:15, TingPing <notifications@github.com> wrote:

> For future release can you change the tags to be x.y.z rather than x-y-z
> as it better integrates with various tools
> ​.
>
>
​Thanks, please could you file an issue about that?

-- 
http://rrt.sc3d.org

**Comment by hfiguiere** [comment]
The old tags are inherited from AbiWord SVN.... I'm totally in agreement on using version numbers for actual releases.
