### ISSUE TITLE
Remove Windows build files

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/enchant#70]
I would like to remove the `msvc` directory. For now, the autotools build system should work on Windows, and if we move to Meson, that will also work.

Any objections?

**Comment by TingPing** [comment]
Probably reasonable, hexchat probably is the biggest deployment of enchant using msvc on Windows and it has a custom nmake makefile: https://github.com/hexchat/gtk-win32/blob/master/enchant/src/makefile.mak

So I'd imagine not many projects depend upon the unmaintained VS projects.

**Comment by rrthomas** [comment]
Closed by PR #75.
