### ISSUE TITLE
Move .NET bindings and tests to a separate project

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/enchant#71]
I don't propose to maintain the .NET bindings (lack of expertise, time and interest), so I propose to move them (`src/bindings/Enchant.Net`) and their tests (`unittests/Enchant.Net.Tests`) to a separate project (suitably extracted from the repo with `git --filter-branch`; or of course it could be directly extracted from subversion?).

**Comment by rrthomas** [comment]
@hfiguiere, I think I need to ask you to do this, as I can't create a new repo in the AbiWord group!

**Comment by hfiguiere** [comment]
Created https://github.com/AbiWord/enchantdotnet

You had admin rights on it (also on enchant now).

**Comment by rrthomas** [comment]
Fixed by PR #78.
