### ISSUE TITLE
`enchant_broker_list_dicts` reports inconsistent providers

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/enchant#8]
The current code for `enchant_broker_list_dicts` simply reports each matched dictionary once. However, it reports the first provider it finds for a given dictionary, so this does not necessarily indicate the preferred provider, which will be providing the dictionary when `enchant_broker_request_dict` is called.

I tried to fix this in two ways. Each had problems:

1. I called `enchant_broker_request_dict` for each tag. This was slow: on my reasonably fast quad-core Sandy Bridge machine, it took about 1.5s of CPU time to list the dictionaries on my system (about 15 or so, for English, French, Dutch and German).
2. I wrote a more complicated check which fetched the provider ordering for each tag, and stored the highest-priority provider for the tag. The trouble is that this doesn't quite work: for example, on my system I have `en_US` and `en_GB` dictionaries provided by myspell, which is the highest-priority provider for `en`. However, myspell does not explicitly provide an `en` dictionary, so the code decides that tag is provided by aspell (which does have such a dictionary), even though `enchant_broker_request_dict` will return a myspell-backed dictionary (because the myspell provider's tag-approximation machinery accepts `en`).

I don't think this bug is terribly important, because I guess most Enchant callers want a list of languages, and don't care about the providers (presumably that is why the bug has not been fixed or indeed perhaps noticed until now).

However, it would be good not actively to provide incorrect information.

I would welcome guidance on where and/or how the bug might most profitably be fixed. I can see various arguments:

1. Approximate matches should be a last resort. For example, suppose I only had `en_ZA` installed with myspell, and had also `en_US` with aspell. Even if my ordering says that myspell should be preferred to aspell for `en`, I might regard it as odd if it picked an `en_ZA` dictionary to spell-check generic `en`. (Or I might not.)
2. Approximate matches should be listed by providers: if a provider will accept a tag, it should list a dictionary for that tag, even if it's effectively a "virtual" dictionary.
3. The right way should be faster: `_enchant_broker_request_dict` (the internal function the implements `enchant_broker_request_dict`) sets up a session for each tag.

**Comment by rrthomas** [comment]
I've done some investigation. Of the 1.5s or so that my "accurate" `enchant_broker_list_dicts` takes, about 400ms is due to the destructors for the `Hunspell` objects backing each myspell dictionary (in my case, most of the dictionaries, about 20). There's not a lot I can do about this (without patching hunspell!).

This suggests that an "obvious and correct" method, i.e. one based on `enchant_broker_request_dict`, is not going to get very far (even though the other 1s or so might be down to enchant code).

For comparison, my "fast and nearly correct" version takes a little under 0.1s to run.

**Comment by rrthomas** [comment]
On further reflection, my "fast" list is arguably correct: it lists actually available dictionaries. In some cases, a different dictionary and provider may be used to check a given tag. I'll submit what I have as a PR.

**Comment by PanderMusubi** [comment]
What is the mechanism for finding a provider?

Check in this order the spell checkers, in order of degrading checking quality: hunspell, myspell, aspell, ispell and spell?

Then, for each spell checker, before going to a spell checker of less quality: find exact language match (match 'en_US' on 'en_US' dict), find less specific match (match 'en_US' on 'en' dict), find more specific match (match 'en' on 'en_US' dict and if missing on 'en_UK' dict and if missing on 'en_CA' and if missing etc)?

**Comment by rrthomas** [comment]
@PanderMusubi the providers are tried in order according to the configuration. Whether a provider offers a dictionary for a given language tag is entirely up to it (which is why it's not possible to replicate exactly inside enchant's main module).

**Comment by rrthomas** [comment]
Closing as fixed by PR #11 as far as possible.
