### ISSUE TITLE
Ensure that Enchant can be used by portable/relocatable applications

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/enchant#86]
Enchant 2.0 will remove ad-hoc support for relocation, but it is required.

**Comment by rrthomas** [comment]
Also, this should have a test (preferably for each OS type supported).

**Comment by TingPing** [comment]
As mentioned elsewhere this would be accomplished by `g_win32_get_package_installation_directory_of_module()` on Windows.

You also removed the proper OSX method in #84 ` [[NSBundle bundleForClass:[self class]] resourcePath];`

For Snaps on Ubuntu you just need to support setting an env var (Snap is just a giant hack full of env vars).

Now on OSX it is largely acceptable to ship a wrapper script that sets env vars but on Windows that is a less common solution, especially when we can easily support doing it "the right way" there.

There is also the use-case of Flatpak which can have multiple paths: `/usr/lib/enchant` `/app/lib/enchant` for example, so it would be needed to support multiple.

**Comment by rrthomas** [comment]
Thanks for putting a comprehensive summary in one place, @TingPing.

What I had envisaged is using an environment variable. Multiple path support would be straightforward, of course.

My understanding is that this applies only to applications that ship an internal copy of Enchant. Are there cases in which a standalone Enchant installation might be expected to be relocatable?

For relocatable applications, an application can, if required, have OS-specific code to set the environment variable. Is there some reason this wouldn't work on Windows?

**Comment by rrthomas** [comment]
gnulib contains a module to address this problem: http://git.savannah.gnu.org/cgit/gnulib.git/tree/modules/relocatable-lib-lgpl

I propose to use this, and if there is something it does not do, to add support to gnulib, so other projects can benefit.

The relevant source is here: http://git.savannah.gnu.org/cgit/gnulib.git/tree/lib/relocatable.h

**Comment by TingPing** [comment]
That seems like a poor solution, We already have GLib and it uses the native win32 api to do the correct thing without weird path hacks.

**Comment by TingPing** [comment]
> My understanding is that this applies only to applications that ship an internal copy of Enchant. Are there cases in which a standalone Enchant installation might be expected to be relocatable?

This is purely for bundling, but the bundled copy comes from a normal enchant build.

**Comment by TingPing** [comment]
> For relocatable applications, an application can, if required, have OS-specific code to set the environment variable. Is there some reason this wouldn't work on Windows?

You don't use wrapper scripts on Windows, nobody wants to write BATCH or something, this is a solved problem in the gnome ecosystem, you just use the correct API and things "Just work".

**Comment by rrthomas** [comment]
I don't understand why any sort of wrapper script is needed; what's wrong with `setenv()`, as used by the tests?

**Comment by TingPing** [comment]
Because that is awful? If enchant just uses the glib api an application has to *nothing* and it works. If you say "Hey application, you have to call `setenv()` and figure it all out yourself, good luck."... then clearly the library is in the wrong.

**Comment by rrthomas** [comment]
Also, I'm trying to see if it's possible to drop glib as a dependency, as this makes it harder to build libenchant. Of course, as long as we do continue to use it, using a glib API is fine (although it is a pity to have to use a platform-specific API, nevertheless the amount of platform-specific code in this case is very small, so that's OK).

**Comment by TingPing** [comment]
Oh god, please don't drop glib... every library doesn't need to reinvent the wheel.

**Comment by rrthomas** [comment]
I don't propose to reinvent the wheel, don't worry. I will see how far it is possible to get with gnulib (no external dependencies) and standard C++.

**Comment by TingPing** [comment]
I know this is just an empty statement but as a user of enchant on all platforms and a potential contributor I find that really disappointing. Gnulib is a very nasty library to work with compared to glib, it is ugly code that is hard to contribute to, that doesn't integrate with all of the glib libraries I already use, and that I have to relearn all over. It would actually be far easier for me to just ship a fork of enchant 1.6.1 that does what I expect it to.

**Comment by rrthomas** [comment]
@TingPing, I appreciate your concern. I don't propose to change the external interface of enchant, or make it harder to build and use.

In terms of external changes in Enchant 2.0, all I plan is a new call to find per-dictionary character classes (issue #17) and a rationalisation of the various configuration mechanisms (env vars, path-finding code etc.). So however the code changes internally, there should be very little impact on a consumer.

As to internal changes, I am working simply to make the code shorter and simpler. Using gnulib is one way I'm doing this (and I will use standard C++ for preference, e.g. for data structures, since there's no reason to stick to C). The gnulib modules I'm using are in two classes: 1) build system helpers, and 2) polyfills for various APIs. I will use standard (POSIX) APIs for preference.

As to contributing, I'm a contributor to gnulib myself, and I've not found it hard, but then maybe it's just a question of familiarity, as I've also contributed to autotools & other related GNU projects. (I have made only very minor contributions to glib etc.)

Anyway, let's see what this ends up looking like. It will be easier to discuss a release candidate. (Similarly for Meson vs GNU autotools: there are some simplifications and improvements I would like to make to the current build system which will make for a better target for comparison with alternatives.)

**Comment by rrthomas** [comment]
(Note that gnulib's relocatable module does use `GetModuleFileName` on Windows, not "weird path hacks"!)

**Comment by rrthomas** [comment]
PR #117 is my attempt to cover this bug. Once the code is merged, I'll document the new interface for review (the old interface was undocumented, and the new one is much simpler).

**Comment by rrthomas** [comment]
Now that PR #117 is merged, it remains to document the new interface.

**Comment by rrthomas** [comment]
Documentation added by PR #122. Closing.
